local render = require("graphics.render")
local render2d = require("graphics.render2d")
local render3d = require("graphics.render3d")
local gfx = require("graphics.gfx")
render.Initialize()
render2d.Initialize()
render3d.Initialize()
gfx.Initialize()
require("game.test_2d")
--require("game.test_3d")
--require("game.test_ecs_debug")
--require("game.test_gltf")
require("game.debug")
