local T = import("test/environment.lua")
local Entity = import("goluwa/entities/entity.lua")
local Vec3 = import("goluwa/structs/vec3.lua")
local BoxShape = import("goluwa/physics/shapes/box.lua")
local SphereShape = import("goluwa/physics/shapes/sphere.lua")
local test_helpers = import("test/tests/physics/test_helpers.lua")

local function spawn_pool(size)
	local ent = Entity.New({Name = "pool"})
	ent:AddComponent("transform")
	ent.transform:SetPosition(Vec3(0, 0, 0))
	ent:AddComponent("water_volume", {Size = size or Vec3(20, 6, 20), Visible = false})
	return ent
end

local function spawn_body(shape, position, density)
	local ent = Entity.New({Name = "floater"})
	ent:AddComponent("transform")
	ent.transform:SetPosition(position)
	local body = ent:AddComponent("rigid_body", {Shape = shape, Density = density, CanSleep = false})
	return ent, body
end

T.TestPhysics("Buoyancy floats a light box at its displacement depth", function()
	local pool = spawn_pool()
	local ent, body = spawn_body(BoxShape.New(Vec3(1, 1, 1)), Vec3(0, 3, 0), 500)
	test_helpers.Simulate(600)
	local y = ent.transform:GetPosition().y
	T(y)[">"](-0.1)
	T(y)["<"](0.1)
	T(body:GetVelocity():GetLength())["<"](0.05)
	T(body.SubmergedFraction)[">"](0.45)
	T(body.SubmergedFraction)["<"](0.55)
	ent:Remove()
	pool:Remove()
end)

T.TestPhysics("Buoyancy lets a dense sphere sink", function()
	local pool = spawn_pool()
	local ent, body = spawn_body(SphereShape.New(0.5), Vec3(0, 2, 0), 3000)
	test_helpers.Simulate(240)
	T(ent.transform:GetPosition().y)["<"](-1)
	ent:Remove()
	pool:Remove()
end)

T.TestPhysics("Buoyancy leaves bodies outside the volume alone", function()
	local pool = spawn_pool(Vec3(4, 6, 4))
	local ent, body = spawn_body(BoxShape.New(Vec3(1, 1, 1)), Vec3(10, 0, 0), 500)
	test_helpers.Simulate(60)
	T(body.SubmergedFraction)["=="](0)
	T(ent.transform:GetPosition().y)["<"](-1)
	ent:Remove()
	pool:Remove()
end)

T.TestPhysics("Buoyancy can be disabled per body", function()
	local pool = spawn_pool()
	local ent, body = spawn_body(BoxShape.New(Vec3(1, 1, 1)), Vec3(0, 3, 0), 500)
	body:SetBuoyancy(0)
	test_helpers.Simulate(240)
	T(ent.transform:GetPosition().y)["<"](-1)
	ent:Remove()
	pool:Remove()
end)

T.TestPhysics("Buoyancy rights a tilted plank", function()
	local pool = spawn_pool()
	local ent, body = spawn_body(BoxShape.New(Vec3(3, 0.3, 0.6)), Vec3(0, 0.5, 0), 400)
	ent.transform:SetAngles(Deg3(0, 0, 40))
	test_helpers.Simulate(900)
	local up = body:GetRotation():VecMul(Vec3(0, 1, 0))
	T(up.y)[">"](0.99)
	T(body:GetAngularVelocity():GetLength())["<"](0.05)
	ent:Remove()
	pool:Remove()
end)

T.TestPhysics("Buoyancy density makes a body float like that material", function()
	local pool = spawn_pool()
	local light, light_body = spawn_body(SphereShape.New(0.5), Vec3(0, 3, 0), 1)
	light_body:SetBuoyancyDensity(500)
	test_helpers.Simulate(600)
	T(light_body.SubmergedFraction)[">"](0.45)
	T(light_body.SubmergedFraction)["<"](0.55)
	light:Remove()
	local human, human_body = spawn_body(SphereShape.New(0.5), Vec3(0, 3, 0), 1)
	human_body:SetBuoyancyDensity(1060)
	test_helpers.Simulate(600)
	T(human.transform:GetPosition().y)["<"](-0.1)
	T(human_body:GetVelocity().y)["<"](0)
	human:Remove()
	pool:Remove()
end)

T.TestPhysics("Buoyancy follows the body's gravity scale", function()
	local pool = spawn_pool()
	local ent, body = spawn_body(BoxShape.New(Vec3(1, 1, 1)), Vec3(0, 3, 0), 500)
	body:SetGravityScale(1.5)
	test_helpers.Simulate(600)
	T(body.SubmergedFraction)[">"](0.45)
	T(body.SubmergedFraction)["<"](0.55)
	ent:Remove()
	pool:Remove()
end)
