local T = require("test.environment")
local ecs = require("ecs")

T.Test("ecs clear world", function()
	ecs.ClearWorld()
	local world = ecs.GetWorld()
	T(#world:GetChildren())["=="](0)
	local e1 = ecs.CreateEntity("e1")
	local e2 = ecs.CreateEntity("e2")
	local e3 = ecs.CreateEntity("e3")
	T(#world:GetChildren())["=="](3)
	ecs.ClearWorld()
	local new_world = ecs.GetWorld()
	T(#new_world:GetChildren())["=="](0)
	T(new_world ~= world)["=="](true)
end)

T.Test("ecs entity recursive removal", function()
	ecs.ClearWorld()
	local world = ecs.GetWorld()
	local parent = ecs.CreateEntity("parent")
	local child1 = ecs.CreateEntity("child1", parent)
	local child2 = ecs.CreateEntity("child2", parent)
	local grandchild = ecs.CreateEntity("grandchild", child1)
	T(#world:GetChildren())["=="](1)
	T(#parent:GetChildren())["=="](2)
	T(#child1:GetChildren())["=="](1)
	parent:Remove()
	-- After removal, they should be invalid (next frame for MakeNULL, but __removed is immediate)
	T(parent:IsValid())["=="](false)
	T(child1:IsValid())["=="](false)
	T(child2:IsValid())["=="](false)
	T(grandchild:IsValid())["=="](false)
	T(#world:GetChildren())["=="](0)
end)
