local test = require("test.gambarina")
require("goluwa.global_environment")
local Ang3 = require("structs.ang3")

test("Ang3 construction", function()
	local a = Ang3(1, 2, 3)
	ok(a.x == 1, "x (pitch) should be 1")
	ok(a.y == 2, "y (yaw) should be 2")
	ok(a.z == 3, "z (roll) should be 3")
end)

test("Ang3 default construction", function()
	local a = Ang3()
	ok(a.x == 0, "pitch should default to 0")
	ok(a.y == 0, "yaw should default to 0")
	ok(a.z == 0, "roll should default to 0")
end)

test("Ang3 copy", function()
	local a1 = Ang3(1, 2, 3)
	local a2 = a1:Copy()
	ok(a2.x == 1, "copied pitch should be 1")
	ok(a2.y == 2, "copied yaw should be 2")
	ok(a2.z == 3, "copied roll should be 3")
	a2.x = 10
	ok(a1.x == 1, "original pitch should still be 1")
end)

test("Ang3 addition", function()
	local a1 = Ang3(1, 2, 3)
	local a2 = Ang3(0.5, 0.5, 0.5)
	local a3 = a1 + a2
	ok(a3.x == 1.5, "pitch should be 1.5")
	ok(a3.y == 2.5, "yaw should be 2.5")
	ok(a3.z == 3.5, "roll should be 3.5")
end)

test("Ang3 Rad/Deg conversion", function()
	local a = Ang3(math.pi, math.pi / 2, 0)
	local deg = a:GetDeg()
	ok(math.abs(deg.x - 180) < 0.0001, "x should be 180 degrees")
	ok(math.abs(deg.y - 90) < 0.0001, "y should be 90 degrees")
	ok(math.abs(deg.z) < 0.0001, "z should be 0 degrees")
end)

test("Ang3 Deg to Rad", function()
	local a = Ang3(180, 90, 45)
	local rad = a:GetRad()
	ok(math.abs(rad.x - math.pi) < 0.0001, "x should be pi radians")
	ok(math.abs(rad.y - math.pi / 2) < 0.0001, "y should be pi/2 radians")
	ok(math.abs(rad.z - math.pi / 4) < 0.0001, "z should be pi/4 radians")
end)

test("Ang3 Normalize", function()
	local a = Ang3(math.pi * 3, -math.pi * 3, math.pi * 5)
	local n = a:GetNormalized()
	ok(n.x >= -math.pi and n.x <= math.pi, "normalized pitch should be in [-pi, pi]")
	ok(n.y >= -math.pi and n.y <= math.pi, "normalized yaw should be in [-pi, pi]")
	ok(n.z >= -math.pi and n.z <= math.pi, "normalized roll should be in [-pi, pi]")
end)

test("Ang3 Lerp", function()
	local a1 = Ang3(0, 0, 0)
	local a2 = Ang3(1, 1, 1)
	local lerped = a1:GetLerped(0.5, a2)
	ok(math.abs(lerped.x - 0.5) < 0.0001, "lerped pitch should be 0.5")
	ok(math.abs(lerped.y - 0.5) < 0.0001, "lerped yaw should be 0.5")
	ok(math.abs(lerped.z - 0.5) < 0.0001, "lerped roll should be 0.5")
end)

test("Ang3 equality", function()
	local a1 = Ang3(1, 2, 3)
	local a2 = Ang3(1, 2, 3)
	local a3 = Ang3(1, 2, 4)
	ok(a1 == a2, "equal angles should be equal")
	ok(not (a1 == a3), "different angles should not be equal")
end)
