local T = import("test/environment.lua")
local ffi = require("ffi")
local Buffer = import("goluwa/structs/buffer.lua")

T.Test("Buffer basic read operations", function()
	local buf = ffi.new("uint8_t[10]", {1, 2, 3, 4, 5, 6, 7, 8, 9, 10})
	local buffer = Buffer.New(buf, 10)
	T(buffer:ReadByte())["=="](1)
	T(buffer:ReadByte())["=="](2)
	T(buffer:ReadByte())["=="](3)
	buffer:Advance(2)
	T(buffer:ReadByte())["=="](6)
	buffer:Advance(-3)
	T(buffer:ReadByte())["=="](4)
end)

T.Test("Buffer string read/write", function()
	local buf = ffi.new("uint8_t[20]")
	local buffer = Buffer.New(buf, 20)
	buffer:WriteStringNonNullterminated("hello world")
	buffer:SetPosition(0)
	local str = buffer:ReadStringNonNullterminated()
	T(str)["=="]("hello world")
end)

T.Test("Buffer varint read/write", function()
	local buf = ffi.new("uint8_t[10]")
	local buffer = Buffer.New(buf, 10)
	buffer:WriteVariableSizedInteger(300)
	buffer:SetPosition(0)
	local val = buffer:ReadVarInt()
	T(val)["=="](300)
end)

T.Test("Buffer half precision float", function()
	local buf = ffi.new("uint8_t[10]")
	local buffer = Buffer.New(buf, 10)
	buffer:WriteHalf(3.14159)
	buffer:SetPosition(0)
	local val = buffer:ReadHalf()
	T(val)["~"](3.140625)
end)

T.Test("Buffer push/pop position", function()
	local buf = ffi.new("uint8_t[10]", {1, 2, 3, 4, 5, 6, 7, 8, 9, 10})
	local buffer = Buffer.New(buf, 10)
	T(buffer:ReadByte())["=="](1)
	buffer:PushPosition(5)
	T(buffer:ReadByte())["=="](6)
	buffer:PopPosition()
	T(buffer:ReadByte())["=="](2)
end)

T.Test("Buffer ReadBits basic", function()
	local buf = ffi.new("uint8_t[2]", {0b10101010, 0b11001100})
	local buffer = Buffer.New(buf, 2)
	buffer:RestartReadBits()
	T(buffer:ReadBits(4))["=="](0xA)
	T(buffer:ReadBits(4))["=="](0xA)
	T(buffer:ReadBits(8))["=="](0xCC)
end)

T.Test("Buffer ReadBits single bits", function()
	local buf = ffi.new("uint8_t[1]", {0b10110100})
	local buffer = Buffer.New(buf, 1)
	buffer:RestartReadBits()
	-- Read LSB to MSB
	T(buffer:ReadBits(1))["=="](0)
	T(buffer:ReadBits(1))["=="](0)
	T(buffer:ReadBits(1))["=="](1)
	T(buffer:ReadBits(1))["=="](0)
	T(buffer:ReadBits(1))["=="](1)
	T(buffer:ReadBits(1))["=="](1)
	T(buffer:ReadBits(1))["=="](0)
	T(buffer:ReadBits(1))["=="](1)
end)

T.Test("Buffer ReadBits various widths", function()
	local buf = ffi.new("uint8_t[4]", {0x12, 0x34, 0x56, 0x78})
	local buffer = Buffer.New(buf, 4)
	buffer:RestartReadBits()
	T(buffer:ReadBits(2))["=="](0x2)
	T(buffer:ReadBits(3))["=="](0x4)
	T(buffer:ReadBits(3))["=="](0x0)
	T(buffer:ReadBits(5))["=="](0x14)
	T(buffer:ReadBits(3))["=="](0x1)
end)

T.Test("Buffer ReadBits 16-bit values", function()
	local buf = ffi.new("uint8_t[2]", {0xFF, 0xFF})
	local buffer = Buffer.New(buf, 2)
	buffer:RestartReadBits()
	local val = buffer:ReadBits(16)
	T(val)["=="](0xFFFF)
end)

T.Test("Buffer ReadBits 24-bit values", function()
	local buf = ffi.new("uint8_t[3]", {0xFF, 0xFF, 0xFF})
	local buffer = Buffer.New(buf, 3)
	buffer:RestartReadBits()
	local val = buffer:ReadBits(24)
	T(val)["=="](0xFFFFFF)
end)

T.Test("Buffer ReadBits 32-bit values", function()
	local buf = ffi.new("uint8_t[4]", {0xFF, 0xFF, 0xFF, 0xFF})
	local buffer = Buffer.New(buf, 4)
	buffer:RestartReadBits()
	local val = buffer:ReadBits(32)
	T(val)["=="](0xFFFFFFFF)
end)

T.Test("Buffer ReadBits 48-bit values", function()
	local buf = ffi.new("uint8_t[6]", {0x76, 0x6F, 0x72, 0x62, 0x69, 0x73})
	local buffer = Buffer.New(buf, 6)
	buffer:RestartReadBits()
	local val = buffer:ReadBits(48)
	T(type(val))["=="]("number")
	T(val)["=="](0x736962726F76)
	T(buffer:RemainingBits())["=="](0)
end)

T.Test("Buffer ReadBits cross-byte boundary", function()
	local buf = ffi.new("uint8_t[2]", {0xAB, 0xCD})
	local buffer = Buffer.New(buf, 2)
	buffer:RestartReadBits()
	T(buffer:ReadBits(8))["=="](0xAB)
	T(buffer:ReadBits(8))["=="](0xCD)
end)

T.Test("Buffer ReadBits zero bits", function()
	local buf = ffi.new("uint8_t[1]", {0xFF})
	local buffer = Buffer.New(buf, 1)
	buffer:RestartReadBits()
	local val = buffer:ReadBits(0)
	T(val)["=="](0)
	T(buffer:ReadBits(8))["=="](0xFF)
end)

T.Test("Buffer ReadBits restart", function()
	local buf = ffi.new("uint8_t[2]", {0xAB, 0xCD})
	local buffer = Buffer.New(buf, 2)
	buffer:RestartReadBits()
	T(buffer:ReadBits(4))["=="](0xB)
	buffer:RestartReadBits()
	T(buffer:ReadBits(4))["=="](0xB)
end)

T.Test("Buffer BitsLeftInByte", function()
	local buf = ffi.new("uint8_t[2]", {0xFF, 0xFF})
	local buffer = Buffer.New(buf, 2)
	buffer:RestartReadBits()
	T(buffer:BitsLeftInByte())["=="](0)
	buffer:ReadBits(3)
	T(buffer:BitsLeftInByte())["=="](5)
	buffer:ReadBits(5)
	T(buffer:BitsLeftInByte())["=="](0)
	buffer:ReadBits(7)
	T(buffer:BitsLeftInByte())["=="](1)
end)

T.Test("Buffer BitPos and RemainingBits with peek", function()
	local buf = ffi.new("uint8_t[2]", {0xAB, 0xCD})
	local buffer = Buffer.New(buf, 2)
	buffer:RestartReadBits()
	T(buffer:BitPos())["=="](0)
	T(buffer:RemainingBits())["=="](16)
	T(buffer:PeekBits(5))["=="](0xB)
	T(buffer:BitPos())["=="](0)
	T(buffer:RemainingBits())["=="](16)
	T(buffer:ReadBits(3))["=="](0x3)
	T(buffer:BitPos())["=="](3)
	T(buffer:RemainingBits())["=="](13)
end)

T.Test("Buffer Read and Peek wrappers", function()
	local buffer = Buffer.New("vorbis\x01")
	buffer:RestartReadBits()
	T(buffer:Peek(48))["=="](0x736962726F76)
	T(buffer:BitPos())["=="](0)
	T(buffer:Read(48))["=="](0x736962726F76)
	T(buffer:Read(8))["=="](1)
	T(buffer:Read(8))["=="](0)
end)

T.Test("Buffer find string", function()
	local buf = ffi.new("uint8_t[20]", "hello world, this is")
	local buffer = Buffer.New(buf, 20)
	local pos = buffer:FindNearest("this")
	T(buffer:GetStringSlice(pos - #"this", pos - 1))["=="]("this")
end)

T.Test("Buffer write mode", function()
	local buf = ffi.new("uint8_t[5]")
	local buffer = Buffer.New(buf, 5):MakeWritable()
	buffer:WriteBytes("hello", 5)
	buffer:SetPosition(0)
	local str = buffer:ReadBytes(5)
	T(str)["=="]("hello")
end)

T.Test("Buffer grow", function()
	local buf = ffi.new("uint8_t[5]")
	local buffer = Buffer.New(buf, 5):MakeWritable()
	buffer:WriteBytes("hello world", 11)
	T(buffer:GetSize())[">="](11)
	buffer:SetPosition(0)
	local str = buffer:ReadBytes(11)
	T(str)["=="]("hello world")
end)

T.Test("Buffer U16 endianness", function()
	local buf = ffi.new("uint8_t[20]")
	local buffer = Buffer.New(buf, 20):MakeWritable()
	buffer:WriteU16LE(0x1234)
	buffer:WriteU16BE(0x1234)
	buffer:SetPosition(0)
	T(buffer:GetByte(0))["=="](0x34)
	T(buffer:GetByte(1))["=="](0x12)
	T(buffer:GetByte(2))["=="](0x12)
	T(buffer:GetByte(3))["=="](0x34)
	buffer:SetPosition(0)
	T(buffer:ReadU16LE())["=="](0x1234)
	T(buffer:ReadU16BE())["=="](0x1234)
end)

T.Test("Buffer U32 endianness", function()
	local buf = ffi.new("uint8_t[20]")
	local buffer = Buffer.New(buf, 20):MakeWritable()
	buffer:WriteU32LE(0x12345678)
	buffer:WriteU32BE(0x12345678)
	buffer:SetPosition(0)
	T(buffer:GetByte(0))["=="](0x78)
	T(buffer:GetByte(1))["=="](0x56)
	T(buffer:GetByte(2))["=="](0x34)
	T(buffer:GetByte(3))["=="](0x12)
	T(buffer:GetByte(4))["=="](0x12)
	T(buffer:GetByte(5))["=="](0x34)
	T(buffer:GetByte(6))["=="](0x56)
	T(buffer:GetByte(7))["=="](0x78)
	buffer:SetPosition(0)
	T(buffer:ReadU32LE())["=="](0x12345678)
	T(buffer:ReadU32BE())["=="](0x12345678)
end)

T.Test("Buffer I32 signed endianness", function()
	local buf = ffi.new("uint8_t[20]")
	local buffer = Buffer.New(buf, 20):MakeWritable()
	buffer:WriteI32LE(-1234567)
	buffer:WriteI32BE(-1234567)
	buffer:SetPosition(0)
	T(buffer:ReadI32LE())["=="](-1234567)
	T(buffer:ReadI32BE())["=="](-1234567)
end)

T.Test("Buffer U64 endianness", function()
	local buf = ffi.new("uint8_t[32]")
	local buffer = Buffer.New(buf, 32):MakeWritable()
	local value = 0x123456789ABCDEF0ULL
	buffer:WriteU64LE(value)
	buffer:WriteU64BE(value)
	buffer:SetPosition(0)
	T(buffer:GetByte(0))["=="](0xF0)
	T(buffer:GetByte(1))["=="](0xDE)
	T(buffer:GetByte(7))["=="](0x12)
	T(buffer:GetByte(8))["=="](0x12)
	T(buffer:GetByte(15))["=="](0xF0)
	buffer:SetPosition(0)
	T(buffer:ReadU64LE())["=="](value)
	T(buffer:ReadU64BE())["=="](value)
end)

T.Test("Buffer Float endianness", function()
	local buf = ffi.new("uint8_t[20]")
	local buffer = Buffer.New(buf, 20):MakeWritable()
	local test_value = 3.14159
	buffer:WriteFloatLE(test_value)
	buffer:WriteFloatBE(test_value)
	buffer:SetPosition(0)
	local le_byte0 = buffer:GetByte(0)
	local be_byte0 = buffer:GetByte(4)
	local le_byte3 = buffer:GetByte(3)
	local be_byte3 = buffer:GetByte(7)
	T(le_byte0)["=="](be_byte3)
	T(le_byte3)["=="](be_byte0)
	buffer:SetPosition(0)
	local read_le = buffer:ReadFloatLE()
	local read_be = buffer:ReadFloatBE()
	T(read_le)["~"](test_value)
	T(read_be)["~"](test_value)
end)

T.Test("Buffer Double endianness", function()
	local buf = ffi.new("uint8_t[32]")
	local buffer = Buffer.New(buf, 32):MakeWritable()
	local test_value = 3.141592653589793
	buffer:WriteDoubleLE(test_value)
	buffer:WriteDoubleBE(test_value)
	buffer:SetPosition(0)
	local le_byte0 = buffer:GetByte(0)
	local be_byte0 = buffer:GetByte(8)
	local le_byte7 = buffer:GetByte(7)
	local be_byte7 = buffer:GetByte(15)
	T(le_byte0)["=="](be_byte7)
	T(le_byte7)["=="](be_byte0)
	buffer:SetPosition(0)
	local read_le = buffer:ReadDoubleLE()
	local read_be = buffer:ReadDoubleBE()
	T(read_le)["~"](test_value)
	T(read_be)["~"](test_value)
end)

T.Test("Buffer I16 endianness", function()
	local buf = ffi.new("uint8_t[20]")
	local buffer = Buffer.New(buf, 20):MakeWritable()
	buffer:WriteI16LE(-12345)
	buffer:WriteI16BE(-12345)
	buffer:SetPosition(0)
	T(buffer:ReadI16LE())["=="](-12345)
	T(buffer:ReadI16BE())["=="](-12345)
end)

T.Test("Buffer I64 endianness", function()
	local buf = ffi.new("uint8_t[32]")
	local buffer = Buffer.New(buf, 32):MakeWritable()
	local value = -9223372036854775807LL
	buffer:WriteI64LE(value)
	buffer:WriteI64BE(value)
	buffer:SetPosition(0)
	T(buffer:ReadI64LE())["=="](value)
	T(buffer:ReadI64BE())["=="](value)
end)

T.Test("Buffer cross-endian compatibility", function()
	local buf = ffi.new("uint8_t[20]")
	local buffer = Buffer.New(buf, 20):MakeWritable()
	buffer:WriteU32LE(0x12345678)
	buffer:SetPosition(0)
	local swapped = buffer:ReadU32BE()
	T(swapped)["=="](0x78563412)
end)

T.Test("Buffer PeekBits basic", function()
	local buf = ffi.new("uint8_t[2]", {0xAB, 0xCD})
	local buffer = Buffer.New(buf, 2)
	buffer:RestartReadBits()
	-- Peek should not consume bits
	T(buffer:PeekBits(4))["=="](0xB)
	T(buffer:PeekBits(4))["=="](0xB)
	T(buffer:PeekBits(8))["=="](0xAB)
	-- Now consume and peek again
	buffer:SkipBits(4)
	T(buffer:PeekBits(4))["=="](0xA)
	T(buffer:PeekBits(8))["=="](0xDA)
end)

T.Test("Buffer PeekBits + SkipBits matches ReadBits", function()
	local buf1 = ffi.new("uint8_t[4]", {0x12, 0x34, 0x56, 0x78})
	local buf2 = ffi.new("uint8_t[4]", {0x12, 0x34, 0x56, 0x78})
	local b1 = Buffer.New(buf1, 4)
	local b2 = Buffer.New(buf2, 4)
	b1:RestartReadBits()
	b2:RestartReadBits()
	-- Read various widths with both methods and compare
	local widths = {3, 5, 7, 1, 8, 4, 4}

	for _, w in ipairs(widths) do
		local v1 = b1:ReadBits(w)
		local v2 = b2:PeekBits(w)
		b2:SkipBits(w)
		T(v1)["=="](v2)
	end
end)

T.Test("Buffer PeekBits 16-bit", function()
	local buf = ffi.new("uint8_t[3]", {0xFF, 0x00, 0xAA})
	local buffer = Buffer.New(buf, 3)
	buffer:RestartReadBits()
	T(buffer:PeekBits(16))["=="](0x00FF)
	buffer:SkipBits(8)
	T(buffer:PeekBits(16))["=="](0xAA00)
end)

T.Test("Buffer NaN handling with endianness", function()
	local buf = ffi.new("uint8_t[32]")
	local buffer = Buffer.New(buf, 32):MakeWritable()
	local nan = 0 / 0
	buffer:WriteFloatLE(nan)
	buffer:WriteFloatBE(nan)
	buffer:WriteDoubleLE(nan)
	buffer:WriteDoubleBE(nan)
	buffer:SetPosition(0)
	local f_le = buffer:ReadFloatLE()
	local f_be = buffer:ReadFloatBE()
	local d_le = buffer:ReadDoubleLE()
	local d_be = buffer:ReadDoubleBE()
	T(f_le ~= f_le)["=="](true)
	T(f_be ~= f_be)["=="](true)
	T(d_le ~= d_le)["=="](true)
	T(d_be ~= d_be)["=="](true)
end)
