local T = require("test.environment")
local orientation = require("render3d.orientation")
local Vec3 = require("structs.vec3")
local Ang3 = require("structs.ang3")
local Quat = require("structs.quat")
local Matrix44 = require("structs.matrix44")

T.Test("orientation vectors are normalized", function()
	T(orientation.UP_VECTOR:GetLength())["~"](1)
	T(orientation.RIGHT_VECTOR:GetLength())["~"](1)
	T(orientation.FORWARD_VECTOR:GetLength())["~"](1)
end)

T.Test("orientation vectors are orthogonal (Y-up, X-right, Z-forward)", function()
	T(orientation.RIGHT_VECTOR.x)["=="](1)
	T(orientation.UP_VECTOR.y)["=="](1)
	T(orientation.FORWARD_VECTOR.z)["=="](-1)
end)

T.Test("Ang3 GetForward at zero rotation", function()
	local a = Ang3(0, 0, 0)
	local fwd = a:GetForward()
	local len = math.sqrt(fwd.x * fwd.x + fwd.y * fwd.y + fwd.z * fwd.z)
	T(len)["~"](1)
end)

T.Test("Ang3 GetUp/Right/Forward at zero rotation", function()
	T(Ang3(0, 0, 0):GetUp())["=="](orientation.UP_VECTOR)
	T(Ang3(0, 0, 0):GetRight())["=="](orientation.RIGHT_VECTOR)
	T(Ang3(0, 0, 0):GetForward())["=="](orientation.FORWARD_VECTOR)
end)

T.Test("Quat directional methods use orientation module", function()
	T(Quat():GetUp())["=="](orientation.UP_VECTOR)
	T(Quat():GetRight())["=="](orientation.RIGHT_VECTOR)
	T(Quat():GetForward())["=="](orientation.FORWARD_VECTOR)
end)

T.Test("Ang3 GetDirection transforms vectors", function()
	T(Ang3(0, 0, 0):GetDirection(orientation.RIGHT_VECTOR))["=="](orientation.RIGHT_VECTOR)
end)

T.Test("Ang3 GetDirection with 90 degree yaw", function()
	T(Ang3(0, math.pi / 2, 0):GetDirection(1, 0, 0):GetLength())["~"](1)
end)

T.Test("Ang3 GetForward with yaw rotation", function()
	T(Ang3(0, math.pi / 2, 0):GetForward():GetLength())["~"](1)
end)

T.Test("Matrix44 rotation helpers use orientation module", function()
	local m = Matrix44()
	local result = m:RotatePitch(0.1)
	T(("%p"):format(result))["=="](("%p"):format(m))
	m:Identity()
	result = m:RotateYaw(0.1)
	T(("%p"):format(result))["=="](("%p"):format(m))
	m:Identity()
	result = m:RotateRoll(0.1)
	T(("%p"):format(result))["=="](("%p"):format(m))
end)

T.Test("Matrix44 Perspective uses orientation Y-flip", function()
	local m = Matrix44()
	m:Perspective(math.pi / 4, 0.1, 1000, 16 / 9)

	if orientation.PROJECTION_Y_FLIP == -1 then
		T(m.m11 < 0)["=="](true)
	else
		T(m.m11 > 0)["=="](true)
	end
end)

T.Pending("Ang3 GetDirection matches Quat VecMul", function()
	local ang = Ang3(0.2, 0.7, -0.3)
	local quat = Quat():SetAngles(ang)
	local test_vec = Vec3(1, 2, 3):GetNormalized()
	local ang_result = ang:GetDirection(test_vec)
	local quat_result = quat:VecMul(test_vec)
	T(ang_result.x)["~"](quat_result.x)
	T(ang_result.y)["~"](quat_result.y)
	T(ang_result.z)["~"](quat_result.z)
end)
