local event = import("goluwa/event.lua")
local render2d = import("goluwa/render2d/render2d.lua")
local Color = import("goluwa/structs/color.lua")
local fonts = import("goluwa/render2d/fonts.lua")
local font = fonts.New{WebName = "Orbitron", Weight = "Regular", Size = 50}

event.AddListener("Draw2D", "test_2d", function()
	local r, g, b, a = Color.FromHex("#08feff"):Unpack()
	render2d.SetColor(r, g, b, a)
	font:DrawText("Hello! Hg", 20, 200)
	render2d.SetColor(1, 0, 0, 0.2)
	render2d.SetTexture(nil)
	local w, h = font:GetTextSize("Hello! Hg")
	render2d.DrawRect(20, 200, w, h)
end)