local T = import("test/environment.lua")

local function assert_close(actual, expected, epsilon)
	epsilon = epsilon or 0.0001
	T(math.abs(actual - expected) <= epsilon)["=="](true)
end

local function new_minimal_love_env()
	local love = {_line_env = {}}
	assert(loadfile("addons/love/lua/libraries/audio.lua"))(love)
	assert(loadfile("addons/love/lua/libraries/sound.lua"))(love)
	return love
end

T.Test("love audio compatibility over SoundData", function()
	local love = new_minimal_love_env()
	local sound_data = love.sound.newSoundData(8, 8, 16, 1)
	local love_source = love.audio.newSource(sound_data)
	T(love_source.__line_type)["=="]("Source")
	T(love_source:getChannels())["=="](1)
	love.audio.setDistanceModel("inverse")
	love.audio.setPosition(7, 8, 9)
	love.audio.setVelocity(1, 2, 3)
	love.audio.setOrientation(0, 0, -1, 0, 1, 0)
	love.audio.setVolume(0.6)
	T(love.audio.getDistanceModel())["=="]("inverse")
	T(({love.audio.getPosition()})[1])["=="](7)
	T(({love.audio.getPosition()})[2])["=="](8)
	T(({love.audio.getPosition()})[3])["=="](9)
	T(({love.audio.getVelocity()})[1])["=="](1)
	T(({love.audio.getVelocity()})[2])["=="](2)
	T(({love.audio.getVelocity()})[3])["=="](3)
	T(({love.audio.getOrientation()})[3])["=="](-1)
	assert_close(love.audio.getVolume(), 0.6)
	love_source:setLooping(true)
	love_source:setPitch(1.25)
	love_source:setVolume(0.4)
	love_source:setPosition(3, 4, 5)
	love_source:setVelocity(6, 7, 8)
	love_source:setDirection(0, 1, 0)
	love_source:setDistance(11, 22)
	love_source:setRolloff(0.9)
	T(love_source:isRelative())["=="](false)
	love_source:setRelative(true)
	T(love_source:isRelative())["=="](true)
	love_source:setRelative(false)
	T(love_source:isLooping())["=="](true)
	T(love_source:isRelative())["=="](false)
	T(love_source:getPitch())["=="](1.25)
	T(love_source:getVolume())["=="](0.4)
	T(({love_source:getPosition()})[1])["=="](3)
	T(({love_source:getPosition()})[2])["=="](4)
	T(({love_source:getPosition()})[3])["=="](5)
	T(({love_source:getVelocity()})[1])["=="](6)
	T(({love_source:getVelocity()})[2])["=="](7)
	T(({love_source:getVelocity()})[3])["=="](8)
	T(({love_source:getDirection()})[1])["=="](0)
	T(({love_source:getDirection()})[2])["=="](1)
	T(({love_source:getDirection()})[3])["=="](0)
	T(({love_source:getDistance()})[1])["=="](11)
	T(({love_source:getDistance()})[2])["=="](22)
	T(love_source:getRolloff())["=="](0.9)
	love_source:play()
	T(love_source:isPlaying())["=="](true)
	love_source:pause()
	T(love_source:isPaused())["=="](true)
	love_source:resume()
	T(love_source:isPlaying())["=="](true)
	love_source:seek(0.25)
	T(love_source:tell())["=="](0.25)
	love_source:stop()
	T(love_source:isStopped())["=="](true)
end)
