local event = import("goluwa/event.lua")
local render = import("goluwa/render/render.lua")
local system = import("goluwa/system.lua")
local render3d = import("goluwa/render3d/render3d.lua")
local Camera3D = import("goluwa/render3d/camera3d.lua")
local timer = import("goluwa/timer.lua")

function Screenshot(pos, rot, fov)
	timer.Delay(0.1, function()
		local cam = render3d.GetCamera()
		cam:SetPosition(pos)
		cam:SetRotation(rot)
		cam:SetFOV(fov or math.rad(90))

		render.Screenshot(function(screenshot_data)
			local path = screenshot_data:Save(nil, true)
			logn("screenshot saved to ", path)
			system.ShutDown(0)
		end)
	end)
end
