local audio = import("goluwa/audio/state.lua")
local spatial = import("goluwa/audio/spatial.lua")
local sound = import("goluwa/audio/sound.lua")
local runtime = import("goluwa/audio/runtime.lua")
local backend = import("goluwa/audio/backend.lua")
spatial.Attach(audio)
sound.Attach(audio)
runtime.Attach(audio)
backend.Attach(audio)
return audio
