local T = import("test/environment.lua")
local ffi = require("ffi")
local audio = import("goluwa/audio.lua")
local event = import("goluwa/event.lua")
local Vec3 = import("goluwa/structs/vec3.lua")

local function new_test_source(sample_count, channels, sample_rate)
	sample_count = sample_count or 8
	channels = channels or 2
	sample_rate = sample_rate or 8
	local data = ffi.new("float[?]", sample_count * channels)

	for i = 0, (sample_count * channels) - 1 do
		data[i] = ((i % channels) + 1) / 10
	end

	local source = audio.CreateSource{
		data = data,
		samples = sample_count,
		channels = channels,
		sample_rate = sample_rate,
	}
	return source, data
end

local function sync_audio_state(dt)
	event.Call("Update", dt or 0)
end

local function assert_close(actual, expected, epsilon)
	epsilon = epsilon or 0.0001
	T(math.abs(actual - expected) <= epsilon)["=="](true)
end

T.Test("audio compatibility API", function()
	audio.StopAll()
	-- Listener state roundtrip.
	audio.SetDistanceModel("linear")
	audio.SetListenerPosition(1, 2, 3)
	audio.SetListenerVelocity(4, 5, 6)
	audio.SetListenerOrientation(0, 0, -1, 0, 1, 0)
	audio.SetListenerGain(0.25)
	T(audio.GetDistanceModel())["=="]("linear")
	T(({audio.GetListenerPosition()})[1])["=="](1)
	T(({audio.GetListenerPosition()})[2])["=="](2)
	T(({audio.GetListenerPosition()})[3])["=="](3)
	T(({audio.GetListenerVelocity()})[1])["=="](4)
	T(({audio.GetListenerVelocity()})[2])["=="](5)
	T(({audio.GetListenerVelocity()})[3])["=="](6)
	T(({audio.GetListenerOrientation()})[1])["=="](0)
	T(({audio.GetListenerOrientation()})[2])["=="](0)
	T(({audio.GetListenerOrientation()})[3])["=="](-1)
	T(({audio.GetListenerOrientation()})[4])["=="](0)
	T(({audio.GetListenerOrientation()})[5])["=="](1)
	T(({audio.GetListenerOrientation()})[6])["=="](0)
	assert_close(audio.GetListenerGain(), 0.25)
	-- Source lifecycle and transport.
	local source = new_test_source(16, 2, 8)
	T(source:IsReady())["=="](true)
	T(source:GetSampleCount())["=="](16)
	T(source:GetDuration())["=="](2)
	T(source:IsPlaying())["=="](false)
	T(source:IsStopped())["=="](true)
	local slot = source:Play()
	T(slot)["~="](nil)
	T(source:IsPlaying())["=="](true)
	T(source:IsPaused())["=="](false)
	T(source:IsStopped())["=="](false)
	source:Pause()
	T(source:IsPaused())["=="](true)
	T(source:IsPlaying())["=="](false)
	local resumed_slot = source:Resume()
	T(resumed_slot)["=="](slot)
	T(source:IsPaused())["=="](false)
	T(source:IsPlaying())["=="](true)
	source:Seek(0.5)
	T(source:Tell())["=="](0.5)
	T(source:Tell("samples"))["=="](4)
	source:Seek(6, "samples")
	T(source:Tell())["=="](0.75)
	T(source:Tell("samples"))["=="](6)
	source:Rewind()
	T(source:Tell())["=="](0)
	source:Stop()
	T(source:IsPlaying())["=="](false)
	T(source:IsPaused())["=="](false)
	T(source:IsStopped())["=="](true)
	T(source:Tell())["=="](0)
	-- Source property compatibility.
	local property_source = new_test_source(8, 1, 4)
	property_source:SetGain(0.5)
	property_source:SetPitch(1.5)
	property_source:SetLooping(true)
	property_source:SetChannel(3)
	property_source:SetPosition(Vec3(10, 20, 30))
	property_source:SetVelocity(Vec3(1, 2, 3))
	property_source:SetDirection(Vec3(-1, 0, 1))
	property_source:SetReferenceDistance(12)
	property_source:SetMaxDistance(48)
	property_source:SetRolloffFactor(0.75)
	T(property_source:GetGain())["=="](0.5)
	T(property_source:GetPitch())["=="](1.5)
	T(property_source:GetLooping())["=="](true)
	T(property_source:GetChannel())["=="](3)
	T(property_source:GetPosition().x)["=="](10)
	T(property_source:GetPosition().y)["=="](20)
	T(property_source:GetPosition().z)["=="](30)
	T(property_source:GetVelocity().x)["=="](1)
	T(property_source:GetVelocity().y)["=="](2)
	T(property_source:GetVelocity().z)["=="](3)
	T(property_source:GetDirection().x)["=="](-1)
	T(property_source:GetDirection().y)["=="](0)
	T(property_source:GetDirection().z)["=="](1)
	T(property_source:GetReferenceDistance())["=="](12)
	T(property_source:GetMaxDistance())["=="](48)
	T(property_source:GetRolloffFactor())["=="](0.75)
	T(property_source:GetChannels())["=="](1)
	-- Spatial attenuation and panning are derived from listener and source transforms.
	audio.SetDistanceModel("inverse")
	audio.SetListenerPosition(0, 0, 0)
	audio.SetListenerOrientation(0, 0, -1, 0, 1, 0)
	property_source:SetReferenceDistance(1)
	property_source:SetMaxDistance(100)
	property_source:SetRolloffFactor(1)
	property_source:SetPosition(Vec3(10, 0, 0))
	local right_mix = audio._ComputeSpatialMixData(property_source)
	assert_close(right_mix.attenuation, 0.1)
	T(right_mix.pan > 0.99)["=="](true)
	T(right_mix.right_gain > right_mix.left_gain)["=="](true)
	property_source:SetPosition(Vec3(-10, 0, 0))
	local left_mix = audio._ComputeSpatialMixData(property_source)
	T(left_mix.pan < -0.99)["=="](true)
	T(left_mix.left_gain > left_mix.right_gain)["=="](true)
	property_source:SetPosition(Vec3(0, 0, -4))
	local center_mix = audio._ComputeSpatialMixData(property_source)
	assert_close(center_mix.pan, 0)
	assert_close(center_mix.left_gain, center_mix.right_gain)
	audio.SetDistanceModel("linear")
	property_source:SetReferenceDistance(1)
	property_source:SetMaxDistance(5)
	property_source:SetRolloffFactor(1)
	property_source:SetPosition(Vec3(3, 0, 0))
	local linear_mix = audio._ComputeSpatialMixData(property_source)
	assert_close(linear_mix.attenuation, 0.5)
	property_source:SetPosition(Vec3(0, 0, 0))
	property_source:SetDirection(Vec3(0, 0, -1))
	property_source:SetCone(60, 120, 0.25)
	audio.SetListenerPosition(0, 0, -10)
	local front_cone_mix = audio._ComputeSpatialMixData(property_source)
	assert_close(front_cone_mix.cone_gain, 1)
	audio.SetListenerPosition(0, 0, 10)
	local rear_cone_mix = audio._ComputeSpatialMixData(property_source)
	assert_close(rear_cone_mix.cone_gain, 0.25)
	audio.SetListenerPosition(10, 0, -10)
	local mid_cone_mix = audio._ComputeSpatialMixData(property_source)
	assert_close(mid_cone_mix.cone_gain, 0.625)
	audio.SetSpeedOfSound(100)
	audio.SetDopplerFactor(1)
	audio.SetListenerPosition(10, 0, 0)
	audio.SetListenerVelocity(0, 0, 0)
	property_source:SetPosition(Vec3(0, 0, 0))
	property_source:SetVelocity(Vec3(10, 0, 0))
	local approaching_mix = audio._ComputeSpatialMixData(property_source)
	assert_close(approaching_mix.doppler_pitch, 100 / 90)
	property_source:SetVelocity(Vec3(-10, 0, 0))
	local receding_mix = audio._ComputeSpatialMixData(property_source)
	assert_close(receding_mix.doppler_pitch, 100 / 110)
	property_source:SetVelocity(Vec3(0, 0, 0))
	audio.SetListenerVelocity(-10, 0, 0)
	local listener_approaching_mix = audio._ComputeSpatialMixData(property_source)
	assert_close(listener_approaching_mix.doppler_pitch, 110 / 100)
	audio.SetListenerVelocity(0, 0, 0)
	audio.SetSpeedOfSound(343.3)
	audio.SetDopplerFactor(1)
	property_source:SetCone(360, 360, 0)
	-- StopAll clears all active voices.
	local source_a = new_test_source(8, 2, 8)
	local source_b = new_test_source(8, 2, 8)
	T(source_a:Play())["~="](nil)
	T(source_b:Play())["~="](nil)
	T(source_a:IsPlaying())["=="](true)
	T(source_b:IsPlaying())["=="](true)
	audio.StopAll()
	sync_audio_state()
	T(source_a:IsPlaying())["=="](false)
	T(source_b:IsPlaying())["=="](false)
	T(source_a:IsStopped())["=="](true)
	T(source_b:IsStopped())["=="](true)
	T(source_a:Tell())["=="](0)
	T(source_b:Tell())["=="](0)
	-- Backend-completed voices propagate playback position back to the source.
	audio.StopAll()
	local released_source = new_test_source(8, 2, 8)
	local slot = released_source:Play()
	T(slot)["~="](nil)
	audio.state.slots[slot].playback_pos = 3
	audio.state.slots[slot].active = false
	sync_audio_state()
	T(released_source:IsPlaying())["=="](false)
	T(released_source:IsPaused())["=="](false)
	T(released_source:IsStopped())["=="](true)
	T(released_source:Tell("samples"))["=="](3)
	T(released_source.slot)["=="](nil)
end)
