require("test.environment")
local Ang3 = require("structs.ang3")

test("Ang3 construction", function()
	eq(Ang3(1, 2, 3), Ang3(1, 2, 3))
end)

test("Ang3 default construction", function()
	local a = Ang3()
	attest.equal(a.x, 0)
	attest.equal(a.y, 0)
	attest.equal(a.z, 0)
end)

test("Ang3 copy", function()
	local a1 = Ang3(1, 2, 3)
	local a2 = a1:Copy()
	attest.equal(a2.x, 1)
	attest.equal(a2.y, 2)
	attest.equal(a2.z, 3)
	a2.x = 10
	attest.equal(a1.x, 1)
end)

test("Ang3 addition", function()
	local a1 = Ang3(1, 2, 3)
	local a2 = Ang3(0.5, 0.5, 0.5)
	local a3 = a1 + a2
	attest.equal(a3.x, 1.5)
	attest.equal(a3.y, 2.5)
	attest.equal(a3.z, 3.5)
end)

test("Ang3 Rad/Deg conversion", function()
	local a = Ang3(math.pi, math.pi / 2, 0)
	local deg = a:GetDeg()
	attest.almost_equal(deg.x, 180)
	attest.almost_equal(deg.y, 90)
	attest.almost_equal(deg.z, 0)
end)

test("Ang3 Deg to Rad", function()
	local a = Ang3(180, 90, 45)
	local rad = a:GetRad()
	attest.almost_equal(rad.x, math.pi)
	attest.almost_equal(rad.y, math.pi / 2)
	attest.almost_equal(rad.z, math.pi / 4)
end)

test("Ang3 Normalize", function()
	local a = Ang3(math.pi * 3, -math.pi * 3, math.pi * 5)
	local n = a:GetNormalized()
	attest.in_range(n.x, -math.pi, math.pi)
	attest.in_range(n.y, -math.pi, math.pi)
	attest.in_range(n.z, -math.pi, math.pi)
end)

test("Ang3 Lerp", function()
	local a1 = Ang3(0, 0, 0)
	local a2 = Ang3(1, 1, 1)
	local lerped = a1:GetLerped(0.5, a2)
	attest.almost_equal(lerped.x, 0.5)
	attest.almost_equal(lerped.y, 0.5)
	attest.almost_equal(lerped.z, 0.5)
end)

test("Ang3 equality", function()
	local a1 = Ang3(1, 2, 3)
	local a2 = Ang3(1, 2, 3)
	local a3 = Ang3(1, 2, 4)
	attest.truthy(a1 == a2)
	attest.falsy(a1 == a3)
end)
