local T = require("test.environment")
local Ang3 = require("structs.ang3")

T.Test("Ang3 construction", function()
	T(Ang3(1, 2, 3))["=="](Ang3(1, 2, 3))
end)

T.Test("Ang3 default construction", function()
	local a = Ang3()
	T(a.x)["=="](0)
	T(a.y)["=="](0)
	T(a.z)["=="](0)
end)

T.Test("Ang3 copy", function()
	local a1 = Ang3(1, 2, 3)
	local a2 = a1:Copy()
	T(a2.x)["=="](1)
	T(a2.y)["=="](2)
	T(a2.z)["=="](3)
	a2.x = 10
	T(a1.x)["=="](1)
end)

T.Test("Ang3 addition", function()
	local a1 = Ang3(1, 2, 3)
	local a2 = Ang3(0.5, 0.5, 0.5)
	local a3 = a1 + a2
	T(a3.x)["=="](1.5)
	T(a3.y)["=="](2.5)
	T(a3.z)["=="](3.5)
end)

T.Test("Ang3 Rad/Deg conversion", function()
	local a = Ang3(math.pi, math.pi / 2, 0)
	local deg = a:GetDeg()
	T(deg.x)["~"](180)
	T(deg.y)["~"](90)
	T(deg.z)["~"](0)
end)

T.Test("Ang3 Deg to Rad", function()
	local a = Ang3(180, 90, 45)
	local rad = a:GetRad()
	T(rad.x)["~"](math.pi)
	T(rad.y)["~"](math.pi / 2)
	T(rad.z)["~"](math.pi / 4)
end)

T.Test("Ang3 Normalize", function()
	local a = Ang3(math.pi * 3, -math.pi * 3, math.pi * 5)
	local n = a:GetNormalized()
	T(n.x)[">="](-math.pi)
	T(n.x)["<="](math.pi)
	T(n.y)[">="](-math.pi)
	T(n.y)["<="](math.pi)
	T(n.z)[">="](-math.pi)
	T(n.z)["<="](math.pi)
end)

T.Test("Ang3 Lerp", function()
	local a1 = Ang3(0, 0, 0)
	local a2 = Ang3(1, 1, 1)
	local lerped = a1:GetLerped(0.5, a2)
	T(lerped.x)["~"](0.5)
	T(lerped.y)["~"](0.5)
	T(lerped.z)["~"](0.5)
end)

T.Test("Ang3 equality", function()
	local a1 = Ang3(1, 2, 3)
	local a2 = Ang3(1, 2, 3)
	local a3 = Ang3(1, 2, 4)
	T(a1 == a2)["=="](true)
	T(a1 == a3)["=="](false)
end)
