require("test.environment")
local ffi = require("ffi")
local Buffer = require("structs.buffer")

test("Buffer basic read operations", function()
	local buf = ffi.new("uint8_t[10]", {1, 2, 3, 4, 5, 6, 7, 8, 9, 10})
	local buffer = Buffer.New(buf, 10)
	attest.equal(buffer:ReadByte(), 1)
	attest.equal(buffer:ReadByte(), 2)
	attest.equal(buffer:ReadByte(), 3)
	buffer:Advance(2)
	attest.equal(buffer:ReadByte(), 6)
	buffer:Advance(-3)
	attest.equal(buffer:ReadByte(), 4)
end)

test("Buffer string read/write", function()
	local buf = ffi.new("uint8_t[20]")
	local buffer = Buffer.New(buf, 20)
	buffer:WriteStringNonNullterminated("hello world")
	buffer:SetPosition(0)
	local str = buffer:ReadStringNonNullterminated()
	attest.equal(str, "hello world")
end)

test("Buffer varint read/write", function()
	local buf = ffi.new("uint8_t[10]")
	local buffer = Buffer.New(buf, 10)
	buffer:WriteVariableSizedInteger(300)
	buffer:SetPosition(0)
	local val = buffer:ReadVarInt()
	attest.equal(val, 300)
end)

test("Buffer half precision float", function()
	local buf = ffi.new("uint8_t[10]")
	local buffer = Buffer.New(buf, 10)
	buffer:WriteHalf(3.14159)
	buffer:SetPosition(0)
	local val = buffer:ReadHalf()
	attest.almost_equal(val, 3.140625)
end)

test("Buffer push/pop position", function()
	local buf = ffi.new("uint8_t[10]", {1, 2, 3, 4, 5, 6, 7, 8, 9, 10})
	local buffer = Buffer.New(buf, 10)
	attest.equal(buffer:ReadByte(), 1)
	buffer:PushPosition(5)
	attest.equal(buffer:ReadByte(), 6)
	buffer:PopPosition()
	attest.equal(buffer:ReadByte(), 2)
end)

test("Buffer ReadBits basic", function()
	local buf = ffi.new("uint8_t[2]", {0b10101010, 0b11001100})
	local buffer = Buffer.New(buf, 2)
	buffer:RestartReadBits()
	attest.equal(buffer:ReadBits(4), 0xA)
	attest.equal(buffer:ReadBits(4), 0xA)
	attest.equal(buffer:ReadBits(8), 0xCC)
end)

test("Buffer ReadBits single bits", function()
	local buf = ffi.new("uint8_t[1]", {0b10110100})
	local buffer = Buffer.New(buf, 1)
	buffer:RestartReadBits()
	-- Read LSB to MSB
	attest.equal(buffer:ReadBits(1), 0)
	attest.equal(buffer:ReadBits(1), 0)
	attest.equal(buffer:ReadBits(1), 1)
	attest.equal(buffer:ReadBits(1), 0)
	attest.equal(buffer:ReadBits(1), 1)
	attest.equal(buffer:ReadBits(1), 1)
	attest.equal(buffer:ReadBits(1), 0)
	attest.equal(buffer:ReadBits(1), 1)
end)

test("Buffer ReadBits various widths", function()
	local buf = ffi.new("uint8_t[4]", {0x12, 0x34, 0x56, 0x78})
	local buffer = Buffer.New(buf, 4)
	buffer:RestartReadBits()
	attest.equal(buffer:ReadBits(2), 0x2)
	attest.equal(buffer:ReadBits(3), 0x4)
	attest.equal(buffer:ReadBits(3), 0x0)
	attest.equal(buffer:ReadBits(5), 0x14)
	attest.equal(buffer:ReadBits(3), 0x1)
end)

test("Buffer ReadBits 16-bit values", function()
	local buf = ffi.new("uint8_t[2]", {0xFF, 0xFF})
	local buffer = Buffer.New(buf, 2)
	buffer:RestartReadBits()
	local val = buffer:ReadBits(16)
	attest.equal(val, 0xFFFF)
end)

test("Buffer ReadBits 24-bit values", function()
	local buf = ffi.new("uint8_t[3]", {0xFF, 0xFF, 0xFF})
	local buffer = Buffer.New(buf, 3)
	buffer:RestartReadBits()
	local val = buffer:ReadBits(24)
	attest.equal(val, 0xFFFFFF)
end)

test("Buffer ReadBits 32-bit values", function()
	local buf = ffi.new("uint8_t[4]", {0xFF, 0xFF, 0xFF, 0xFF})
	local buffer = Buffer.New(buf, 4)
	buffer:RestartReadBits()
	local val = buffer:ReadBits(32)
	attest.equal(val, 0xFFFFFFFF)
end)

test("Buffer ReadBits cross-byte boundary", function()
	local buf = ffi.new("uint8_t[2]", {0xAB, 0xCD})
	local buffer = Buffer.New(buf, 2)
	buffer:RestartReadBits()
	attest.equal(buffer:ReadBits(8), 0xAB)
	attest.equal(buffer:ReadBits(8), 0xCD)
end)

test("Buffer ReadBits zero bits", function()
	local buf = ffi.new("uint8_t[1]", {0xFF})
	local buffer = Buffer.New(buf, 1)
	buffer:RestartReadBits()
	local val = buffer:ReadBits(0)
	attest.equal(val, 0)
	attest.equal(buffer:ReadBits(8), 0xFF)
end)

test("Buffer ReadBits restart", function()
	local buf = ffi.new("uint8_t[2]", {0xAB, 0xCD})
	local buffer = Buffer.New(buf, 2)
	buffer:RestartReadBits()
	attest.equal(buffer:ReadBits(4), 0xB)
	buffer:RestartReadBits()
	attest.equal(buffer:ReadBits(4), 0xB)
end)

test("Buffer BitsLeftInByte", function()
	local buf = ffi.new("uint8_t[2]", {0xFF, 0xFF})
	local buffer = Buffer.New(buf, 2)
	buffer:RestartReadBits()
	attest.equal(buffer:BitsLeftInByte(), 0)
	buffer:ReadBits(3)
	attest.equal(buffer:BitsLeftInByte(), 5)
	buffer:ReadBits(5)
	attest.equal(buffer:BitsLeftInByte(), 0)
	buffer:ReadBits(7)
	attest.equal(buffer:BitsLeftInByte(), 1)
end)

test("Buffer find string", function()
	local buf = ffi.new("uint8_t[20]", "hello world, this is")
	local buffer = Buffer.New(buf, 20)
	local pos = buffer:FindNearest("this")
	attest.equal(buffer:GetStringSlice(pos - #"this", pos - 1), "this")
end)

test("Buffer write mode", function()
	local buf = ffi.new("uint8_t[5]")
	local buffer = Buffer.New(buf, 5):MakeWritable()
	buffer:WriteBytes("hello", 5)
	buffer:SetPosition(0)
	local str = buffer:ReadBytes(5)
	attest.equal(str, "hello")
end)

test("Buffer grow", function()
	local buf = ffi.new("uint8_t[5]")
	local buffer = Buffer.New(buf, 5):MakeWritable()
	buffer:WriteBytes("hello world", 11)
	attest.greater_or_equal(buffer:GetSize(), 11)
	buffer:SetPosition(0)
	local str = buffer:ReadBytes(11)
	attest.equal(str, "hello world")
end)

test("Buffer U16 endianness", function()
	local buf = ffi.new("uint8_t[20]")
	local buffer = Buffer.New(buf, 20):MakeWritable()
	buffer:WriteU16LE(0x1234)
	buffer:WriteU16BE(0x1234)
	buffer:SetPosition(0)
	attest.equal(buffer:GetByte(0), 0x34)
	attest.equal(buffer:GetByte(1), 0x12)
	attest.equal(buffer:GetByte(2), 0x12)
	attest.equal(buffer:GetByte(3), 0x34)
	buffer:SetPosition(0)
	attest.equal(buffer:ReadU16LE(), 0x1234)
	attest.equal(buffer:ReadU16BE(), 0x1234)
end)

test("Buffer U32 endianness", function()
	local buf = ffi.new("uint8_t[20]")
	local buffer = Buffer.New(buf, 20):MakeWritable()
	buffer:WriteU32LE(0x12345678)
	buffer:WriteU32BE(0x12345678)
	buffer:SetPosition(0)
	attest.equal(buffer:GetByte(0), 0x78)
	attest.equal(buffer:GetByte(1), 0x56)
	attest.equal(buffer:GetByte(2), 0x34)
	attest.equal(buffer:GetByte(3), 0x12)
	attest.equal(buffer:GetByte(4), 0x12)
	attest.equal(buffer:GetByte(5), 0x34)
	attest.equal(buffer:GetByte(6), 0x56)
	attest.equal(buffer:GetByte(7), 0x78)
	buffer:SetPosition(0)
	attest.equal(buffer:ReadU32LE(), 0x12345678)
	attest.equal(buffer:ReadU32BE(), 0x12345678)
end)

test("Buffer I32 signed endianness", function()
	local buf = ffi.new("uint8_t[20]")
	local buffer = Buffer.New(buf, 20):MakeWritable()
	buffer:WriteI32LE(-1234567)
	buffer:WriteI32BE(-1234567)
	buffer:SetPosition(0)
	attest.equal(buffer:ReadI32LE(), -1234567)
	attest.equal(buffer:ReadI32BE(), -1234567)
end)

test("Buffer U64 endianness", function()
	local buf = ffi.new("uint8_t[32]")
	local buffer = Buffer.New(buf, 32):MakeWritable()
	local value = 0x123456789ABCDEF0ULL
	buffer:WriteU64LE(value)
	buffer:WriteU64BE(value)
	buffer:SetPosition(0)
	attest.equal(buffer:GetByte(0), 0xF0)
	attest.equal(buffer:GetByte(1), 0xDE)
	attest.equal(buffer:GetByte(7), 0x12)
	attest.equal(buffer:GetByte(8), 0x12)
	attest.equal(buffer:GetByte(15), 0xF0)
	buffer:SetPosition(0)
	attest.equal(buffer:ReadU64LE(), value)
	attest.equal(buffer:ReadU64BE(), value)
end)

test("Buffer Float endianness", function()
	local buf = ffi.new("uint8_t[20]")
	local buffer = Buffer.New(buf, 20):MakeWritable()
	local test_value = 3.14159
	buffer:WriteFloatLE(test_value)
	buffer:WriteFloatBE(test_value)
	buffer:SetPosition(0)
	local le_byte0 = buffer:GetByte(0)
	local be_byte0 = buffer:GetByte(4)
	local le_byte3 = buffer:GetByte(3)
	local be_byte3 = buffer:GetByte(7)
	attest.equal(le_byte0, be_byte3)
	attest.equal(le_byte3, be_byte0)
	buffer:SetPosition(0)
	local read_le = buffer:ReadFloatLE()
	local read_be = buffer:ReadFloatBE()
	attest.almost_equal(read_le, test_value, 0.00001)
	attest.almost_equal(read_be, test_value, 0.00001)
end)

test("Buffer Double endianness", function()
	local buf = ffi.new("uint8_t[32]")
	local buffer = Buffer.New(buf, 32):MakeWritable()
	local test_value = 3.141592653589793
	buffer:WriteDoubleLE(test_value)
	buffer:WriteDoubleBE(test_value)
	buffer:SetPosition(0)
	local le_byte0 = buffer:GetByte(0)
	local be_byte0 = buffer:GetByte(8)
	local le_byte7 = buffer:GetByte(7)
	local be_byte7 = buffer:GetByte(15)
	attest.equal(le_byte0, be_byte7)
	attest.equal(le_byte7, be_byte0)
	buffer:SetPosition(0)
	local read_le = buffer:ReadDoubleLE()
	local read_be = buffer:ReadDoubleBE()
	attest.almost_equal(read_le, test_value, 0.000000000001)
	attest.almost_equal(read_be, test_value, 0.000000000001)
end)

test("Buffer I16 endianness", function()
	local buf = ffi.new("uint8_t[20]")
	local buffer = Buffer.New(buf, 20):MakeWritable()
	buffer:WriteI16LE(-12345)
	buffer:WriteI16BE(-12345)
	buffer:SetPosition(0)
	attest.equal(buffer:ReadI16LE(), -12345)
	attest.equal(buffer:ReadI16BE(), -12345)
end)

test("Buffer I64 endianness", function()
	local buf = ffi.new("uint8_t[32]")
	local buffer = Buffer.New(buf, 32):MakeWritable()
	local value = -9223372036854775807LL
	buffer:WriteI64LE(value)
	buffer:WriteI64BE(value)
	buffer:SetPosition(0)
	attest.equal(buffer:ReadI64LE(), value)
	attest.equal(buffer:ReadI64BE(), value)
end)

test("Buffer cross-endian compatibility", function()
	local buf = ffi.new("uint8_t[20]")
	local buffer = Buffer.New(buf, 20):MakeWritable()
	buffer:WriteU32LE(0x12345678)
	buffer:SetPosition(0)
	local swapped = buffer:ReadU32BE()
	attest.equal(swapped, 0x78563412)
end)

test("Buffer NaN handling with endianness", function()
	local buf = ffi.new("uint8_t[32]")
	local buffer = Buffer.New(buf, 32):MakeWritable()
	local nan = 0 / 0
	buffer:WriteFloatLE(nan)
	buffer:WriteFloatBE(nan)
	buffer:WriteDoubleLE(nan)
	buffer:WriteDoubleBE(nan)
	buffer:SetPosition(0)
	local f_le = buffer:ReadFloatLE()
	local f_be = buffer:ReadFloatBE()
	local d_le = buffer:ReadDoubleLE()
	local d_be = buffer:ReadDoubleBE()
	attest.truthy(f_le ~= f_le)
	attest.truthy(f_be ~= f_be)
	attest.truthy(d_le ~= d_le)
	attest.truthy(d_be ~= d_be)
end)
