local T = require("test.t")
local threads = require("bindings.threads")

T.test("thread returns incremented value", function()
	local thread = threads.new(function(input)
		assert(input == 1)
		return input + 1
	end)
	thread:run(1)
	local ret = thread:join()
	T(ret)["=="](2)
end)

T.test("thread handles errors", function()
	local thread = threads.new(function(input)
		error("Intentional Error")
	end)
	thread:run(1)
	local ret, err = thread:join()
	T(err)["~="](nil)
	T(err:find("Intentional Error"))["~="](nil)
end)
