require("test.environment")
local Vec3 = require("structs.vec3")

test("Vec3 construction", function()
	local v = Vec3(1, 2, 3)
	ok(v.x == 1, "x should be 1")
	ok(v.y == 2, "y should be 2")
	ok(v.z == 3, "z should be 3")
end)

test("Vec3 default construction", function()
	local v = Vec3()
	ok(v.x == 0, "x should default to 0")
	ok(v.y == 0, "y should default to 0")
	ok(v.z == 0, "z should default to 0")
end)

test("Vec3 copy", function()
	local v1 = Vec3(1, 2, 3)
	local v2 = v1:Copy()
	ok(v2.x == 1, "copied x should be 1")
	ok(v2.y == 2, "copied y should be 2")
	ok(v2.z == 3, "copied z should be 3")
	v2.x = 10
	ok(v1.x == 1, "original x should still be 1")
end)

test("Vec3 addition", function()
	local v1 = Vec3(1, 2, 3)
	local v2 = Vec3(4, 5, 6)
	local v3 = v1 + v2
	ok(v3.x == 5, "x should be 5")
	ok(v3.y == 7, "y should be 7")
	ok(v3.z == 9, "z should be 9")
end)

test("Vec3 subtraction", function()
	local v1 = Vec3(5, 7, 9)
	local v2 = Vec3(1, 2, 3)
	local v3 = v1 - v2
	ok(v3.x == 4, "x should be 4")
	ok(v3.y == 5, "y should be 5")
	ok(v3.z == 6, "z should be 6")
end)

test("Vec3 scalar multiplication", function()
	local v = Vec3(1, 2, 3)
	local v2 = v * 2
	ok(v2.x == 2, "x should be 2")
	ok(v2.y == 4, "y should be 4")
	ok(v2.z == 6, "z should be 6")
end)

test("Vec3 scalar division", function()
	local v = Vec3(2, 4, 6)
	local v2 = v / 2
	ok(v2.x == 1, "x should be 1")
	ok(v2.y == 2, "y should be 2")
	ok(v2.z == 3, "z should be 3")
end)

test("Vec3 dot product", function()
	local v1 = Vec3(1, 2, 3)
	local v2 = Vec3(4, 5, 6)
	local dot = v1:GetDot(v2)
	ok(dot == 32, "dot product should be 32 (1*4 + 2*5 + 3*6)")
end)

test("Vec3 cross product", function()
	local v1 = Vec3(1, 0, 0)
	local v2 = Vec3(0, 1, 0)
	local cross = v1:GetCross(v2)
	ok(cross.x == 0, "x should be 0")
	ok(cross.y == 0, "y should be 0")
	ok(cross.z == 1, "z should be 1")
end)

test("Vec3 cross product - inverse order", function()
	local v1 = Vec3(0, 1, 0)
	local v2 = Vec3(1, 0, 0)
	local cross = v1:GetCross(v2)
	ok(cross.x == 0, "x should be 0")
	ok(cross.y == 0, "y should be 0")
	ok(cross.z == -1, "z should be -1")
end)

test("Vec3 length", function()
	local v = Vec3(3, 4, 0)
	local len = v:GetLength()
	ok(math.abs(len - 5) < 0.0001, "length should be 5")
end)

test("Vec3 length 3D", function()
	local v = Vec3(1, 2, 2)
	local len = v:GetLength()
	ok(math.abs(len - 3) < 0.0001, "length should be 3")
end)

test("Vec3 normalize", function()
	local v = Vec3(3, 4, 0)
	local n = v:GetNormalized()
	ok(math.abs(n.x - 0.6) < 0.0001, "normalized x should be 0.6")
	ok(math.abs(n.y - 0.8) < 0.0001, "normalized y should be 0.8")
	ok(math.abs(n.z) < 0.0001, "normalized z should be 0")
	ok(math.abs(n:GetLength() - 1) < 0.0001, "normalized length should be 1")
end)

test("Vec3 negation", function()
	local v = Vec3(1, -2, 3)
	local neg = -v
	ok(neg.x == -1, "x should be -1")
	ok(neg.y == 2, "y should be 2")
	ok(neg.z == -3, "z should be -3")
end)

test("Vec3 equality", function()
	local v1 = Vec3(1, 2, 3)
	local v2 = Vec3(1, 2, 3)
	local v3 = Vec3(1, 2, 4)
	ok(v1 == v2, "equal vectors should be equal")
	ok(not (v1 == v3), "different vectors should not be equal")
end)

test("Vec3 GetAngles", function()
	local v = Vec3(1, 0, 0)
	local ang = v:GetAngles()
	-- Pointing along x-axis should give specific angles
	ok(ang ~= nil, "GetAngles should return an Ang3")
end)
