local T = import("test/environment.lua")
local ffi = require("ffi")
local render = import("goluwa/render/render.lua")
local render2d = import("goluwa/render2d/render2d.lua")
local fs = import("goluwa/filesystem/fs.lua")
local Vec2 = import("goluwa/structs/vec2.lua")
local Vec3 = import("goluwa/structs/vec3.lua")
local Color = import("goluwa/structs/color.lua")

T.Test2D("Graphics render2d SetUV is idempotent - GetUV returns original params", function()
	-- SetUV must store original parameters, not transformed ones
	render2d.SetSDFScaledUVFlippedY(10, 20, 100, 200, 512, 512)
	local x, y, w, h, sx, sy = render2d.GetSDFScaledUVFlippedY()
	T(x)["=="](10)
	T(y)["=="](20)
	T(w)["=="](100)
	T(h)["=="](200)
	T(sx)["=="](512)
	T(sy)["=="](512)
	-- GetUV then SetUV with returned values should be idempotent
	render2d.SetSDFScaledUVFlippedY(x, y, w, h, sx, sy)
	x, y, w, h, sx, sy = render2d.GetSDFScaledUVFlippedY()
	T(x)["=="](10)
	T(y)["=="](20)
	T(w)["=="](100)
	T(h)["=="](200)
	T(sx)["=="](512)
	T(sy)["=="](512)
end)

T.Test2D("Graphics render2d PushUV PopUV roundtrip", function()
	render2d.SetSDFScaledUVFlippedY(10, 20, 30, 40, 100, 100)
	render2d.PushSDFScaledUVFlippedY(50, 60, 70, 80, 200, 200)
	local x, y, w, h, sx, sy = render2d.GetSDFScaledUVFlippedY()
	T(x)["=="](50)
	T(y)["=="](60)
	T(w)["=="](70)
	T(h)["=="](80)
	T(sx)["=="](200)
	T(sy)["=="](200)
	render2d.PopSDFScaledUVFlippedY()
	x, y, w, h, sx, sy = render2d.GetSDFScaledUVFlippedY()
	T(x)["=="](10)
	T(y)["=="](20)
	T(w)["=="](30)
	T(h)["=="](40)
	T(sx)["=="](100)
	T(sy)["=="](100)
end)

T.Test2D("Graphics render2d nested PushUV PopUV", function()
	render2d.SetSDFScaledUVFlippedY(1, 2, 3, 4, 10, 10)
	render2d.PushSDFScaledUVFlippedY(10, 20, 30, 40, 100, 100)
	render2d.PushSDFScaledUVFlippedY(100, 200, 300, 400, 1000, 1000)
	local x, y = render2d.GetSDFScaledUVFlippedY()
	T(x)["=="](100)
	T(y)["=="](200)
	render2d.PopSDFScaledUVFlippedY()
	x, y = render2d.GetSDFScaledUVFlippedY()
	T(x)["=="](10)
	T(y)["=="](20)
	render2d.PopSDFScaledUVFlippedY()
	x, y = render2d.GetSDFScaledUVFlippedY()
	T(x)["=="](1)
	T(y)["=="](2)
end)

T.Test2D("Graphics render2d SetUV transform constants are correct", function()
	-- UV offset/scale should be computed from pixel coords divided by scale
	render2d.SetSDFScaledUVFlippedY(100, 200, 50, 100, 1024, 1024)
	local off_x, off_y, scale_x, scale_y = render2d.GetSDFUVTransformed()
	T(off_x)["~"](100 / 1024)
	T(off_y)["~"]((-200 - 100) / 1024) -- y_transformed = -y - h
	T(scale_x)["~"](50 / 1024)
	T(scale_y)["~"](100 / 1024)
end)

T.Test2D("Graphics render2d SetSDFUV GetSDFUVTransformed", function()
	render2d.SetSDFUV(0.1, 0.2, 0.9, 0.8)
	local off_x, off_y, scale_x, scale_y = render2d.GetSDFUVTransformed()
	T(off_x)["~"](0.1)
	T(off_y)["~"](0.2)
	T(scale_x)["~"](0.8) -- u2 - u1
	T(scale_y)["~"](0.6) -- v2 - v1 = 0.8 - 0.2
end)

T.Test2D("Graphics render2d SetSDFUV does not affect GetUV state", function()
	render2d.SetSDFScaledUVFlippedY(50, 60, 70, 80, 256, 256)
	local x, y = render2d.GetSDFScaledUVFlippedY()
	T(x)["=="](50)
	T(y)["=="](60)
	-- SetSDFUV only changes fragment constants, not the uv state object
	render2d.SetSDFUV(0.5, 0.5, 1.0, 1.0)
	x, y = render2d.GetSDFScaledUVFlippedY()
	T(x)["=="](50)
	T(y)["=="](60)
end)

T.Test2D("Graphics render2d PushUV PopUV preserves transform state", function()
	render2d.SetSDFScaledUVFlippedY(10, 20, 30, 40, 100, 100)
	render2d.PushSDFScaledUVFlippedY(50, 60, 70, 80, 200, 200)
	-- After push, both GetUV and GetSDFUVTransformed should reflect pushed state
	local x, y = render2d.GetSDFScaledUVFlippedY()
	T(x)["=="](50)
	T(y)["=="](60)
	local off_x, off_y, scale_x, scale_y = render2d.GetSDFUVTransformed()
	T(off_x)["~"](50 / 200)
	T(off_y)["~"]((-60 - 80) / 200)
	render2d.PopSDFScaledUVFlippedY()
	-- After pop, should restore original state
	x, y = render2d.GetSDFScaledUVFlippedY()
	T(x)["=="](10)
	T(y)["=="](20)
	off_x, off_y, scale_x, scale_y = render2d.GetSDFUVTransformed()
	T(off_x)["~"](10 / 100)
	T(off_y)["~"]((-20 - 40) / 100)
end)

T.Test2D("Graphics render2d PushUV PopUV after SetSDFUV preserves SetUV state", function()
	-- SetSDFUV only changes fragment constants, not the uv state object
	render2d.SetSDFScaledUVFlippedY(10, 20, 30, 40, 100, 100)
	render2d.SetSDFUV(0.1, 0.2, 0.9, 0.8) -- changes constants but not uv state
	-- PushUV saves the uv state (from SetUV), not the constants
	render2d.PushSDFScaledUVFlippedY(50, 60, 70, 80, 200, 200)
	local x, y = render2d.GetSDFScaledUVFlippedY()
	T(x)["=="](50)
	T(y)["=="](60)
	render2d.PopSDFScaledUVFlippedY()
	-- After pop, uv state should be restored to SetUV values (not SetSDFUV)
	x, y = render2d.GetSDFScaledUVFlippedY()
	T(x)["=="](10)
	T(y)["=="](20)
	-- But GetSDFUVTransformed should reflect the SetUV transform, not SetSDFUV
	local off_x, off_y, scale_x, scale_y = render2d.GetSDFUVTransformed()
	T(off_x)["~"](10 / 100)
	T(off_y)["~"]((-20 - 40) / 100)
end)

T.Test2D("Graphics render2d PushUV no args resets to default", function()
	render2d.SetSDFScaledUVFlippedY(10, 20, 30, 40, 100, 100)
	-- PushSDFScaledUVFlippedY() with no args: saves current state, calls SetUV(nil) which resets
	render2d.PushSDFScaledUVFlippedY()
	local x = render2d.GetSDFScaledUVFlippedY()
	T(x)["=="](nil) -- reset returns nil for x
	render2d.PopSDFScaledUVFlippedY()
	x = render2d.GetSDFScaledUVFlippedY()
	T(x)["=="](10)
end)

T.Test2D("Graphics render2d PushUV2 PopUV2 roundtrip", function()
	render2d.SetSDFUV(0.1, 0.2, 0.9, 0.8)
	local off_x, off_y, scale_x, scale_y = render2d.GetSDFUVTransformed()
	T(off_x)["~"](0.1)
	T(off_y)["~"](0.2)
	T(scale_x)["~"](0.8)
	T(scale_y)["~"](0.6)
	render2d.PushSDFUV(0.0, 0.0, 1.0, 1.0)
	off_x, off_y, scale_x, scale_y = render2d.GetSDFUVTransformed()
	T(off_x)["~"](0.0)
	T(off_y)["~"](0.0)
	T(scale_x)["~"](1.0)
	T(scale_y)["~"](1.0)
	render2d.PopSDFUV()
	off_x, off_y, scale_x, scale_y = render2d.GetSDFUVTransformed()
	T(off_x)["~"](0.1)
	T(off_y)["~"](0.2)
	T(scale_x)["~"](0.8)
	T(scale_y)["~"](0.6)
end)

T.Test2D("Graphics render2d PushUV2 no args resets to default", function()
	render2d.SetSDFUV(0.5, 0.5, 1.0, 1.0)
	render2d.PushSDFUV()
	-- GetUV2 returns nil after reset (state object cleared)
	local u1 = render2d.GetSDFUV()
	T(u1)["=="](0)
	-- But GetSDFUVTransformed returns default constant values
	local off_x, off_y, scale_x, scale_y = render2d.GetSDFUVTransformed()
	T(off_x)["=="](0.0)
	T(off_y)["=="](0.0)
	T(scale_x)["=="](1.0)
	T(scale_y)["=="](1.0)
	render2d.PopSDFUV()
	u1 = render2d.GetSDFUV()
	T(u1)["~"](0.5)
end)

T.Test2D("Graphics render2d nested PushUV2 PopUV2", function()
	render2d.SetSDFUV(0.0, 0.0, 0.5, 0.5)
	render2d.PushSDFUV(0.1, 0.1, 0.9, 0.9)
	render2d.PushSDFUV(0.25, 0.25, 0.75, 0.75)
	local off_x, off_y, scale_x, scale_y = render2d.GetSDFUVTransformed()
	T(off_x)["~"](0.25)
	T(off_y)["~"](0.25)
	T(scale_x)["~"](0.5)
	T(scale_y)["~"](0.5)
	render2d.PopSDFUV()
	off_x, off_y, scale_x, scale_y = render2d.GetSDFUVTransformed()
	T(off_x)["~"](0.1)
	T(off_y)["~"](0.1)
	T(scale_x)["~"](0.8)
	T(scale_y)["~"](0.8)
	render2d.PopSDFUV()
	off_x, off_y, scale_x, scale_y = render2d.GetSDFUVTransformed()
	T(off_x)["~"](0.0)
	T(off_y)["~"](0.0)
	T(scale_x)["~"](0.5)
	T(scale_y)["~"](0.5)
end)

T.Test2D("Graphics render2d preserves fragment constant values across resolved storage", function()
	render2d.SetSDFUV(0.25, 0.5, 0.75, 1.0)
	render2d.SetSDFSoftness(3)
	render2d.SetBorderRadius(1, 2, 3, 4)
	render2d.SetOutlineWidth(6)
	render2d.SetNinePatch(10, 20, 30, 40, 0)
	render2d.UploadConstants()
	local draw = render2d.pipeline:GetConstantBlockInfo("draw")
	local shape = render2d.pipeline:GetConstantBlockInfo("shape")
	local patch = render2d.pipeline:GetConstantBlockInfo("nine_patch")
	local draw_data = render2d.pipeline:BuildConstantBlockData("draw")
	local shape_data = render2d.pipeline:BuildConstantBlockData("shape")
	local patch_data = render2d.pipeline:BuildConstantBlockData("nine_patch")
	T(draw.storage == "push" or draw.storage == "uniform_buffer")["=="](true)
	T(shape.storage == "push" or shape.storage == "uniform_buffer")["=="](true)
	T(patch.storage == "push" or patch.storage == "uniform_buffer")["=="](true)
	T(draw_data.uv_offset[0])["=="](0.25)
	T(draw_data.uv_offset[1])["=="](0.5)
	T(draw_data.uv_scale[0])["=="](0.5)
	T(draw_data.uv_scale[1])["=="](0.5)
	T(shape_data.border_radius[0])["=="](1)
	T(shape_data.border_radius[1])["=="](2)
	T(shape_data.border_radius[2])["=="](3)
	T(shape_data.border_radius[3])["=="](4)
	T(shape_data.outline_width)["=="](6)
	T(patch_data.nine_patch_x_count)["=="](1)
	T(patch_data.nine_patch_y_count)["=="](1)
	T(patch_data.nine_patch_x_stretch[0])["=="](10)
	T(patch_data.nine_patch_x_stretch[1])["=="](20)
	T(patch_data.nine_patch_y_stretch[0])["=="](30)
	T(patch_data.nine_patch_y_stretch[1])["=="](40)
end)
