local T = import("test/environment.lua")
local render2d = import("goluwa/render2d/render2d.lua")
local steam = import("goluwa/steam/steam.lua")
local Material = import("goluwa/render3d/material.lua")

T.Test2D("VMT render", function()
	local games = steam.GetSourceGames()
	steam.MountSourceGame("gmod")
	local mat = Material.FromVMT("materials/models/hevsuit/hevsuit_sheet.vmt")
	render2d.SetColor(1, 0, 0, 1)
	render2d.SetTexture(mat:GetAlbedoTexture())
	render2d.DrawRect(0, 0, 50, 50)
end)
