local T = import("test/environment.lua")
_G.CLIENT = true
_G.SERVER = true
_G.e = _G.e or {USERNAME = "testuser"}

-- Add Color constructor if not present (needed by client:GetUniqueColor)
if not _G.Color then
	_G.Color = function(r, g, b, a)
		local c = {r = r or 0, g = g or 0, b = b or 0, a = a or 255}

		function c:SetLightness(lightness)
			self.r = math.min(255, math.max(0, self.r * lightness))
			self.g = math.min(255, math.max(0, self.g * lightness))
			self.b = math.min(255, math.max(0, self.b * lightness))
			return self
		end

		return c
	end
end

local clients = import("goluwa/network/clients.lua")
clients.Initialize()

T.Test("Clients registry creates and retrieves client", function()
	local client = clients.Create("registry_test_1", false)
	T(client:IsValid())["=="](true)
	T(client:GetUniqueID())["=="]("registry_test_1")
	local retrieved = clients.GetByUniqueID("registry_test_1")
	T(retrieved:IsValid())["=="](true)
	T(retrieved:GetUniqueID())["=="]("registry_test_1")
	client:Remove()
end)

T.Test("Clients registry multiple clients", function()
	local client1 = clients.Create("multi_test_1", false)
	local client2 = clients.Create("multi_test_2", false)
	local client3 = clients.Create("multi_test_3", false)
	T(#clients.GetAll())["=="](4)
	T(clients.GetByUniqueID("multi_test_1"):IsValid())["=="](true)
	T(clients.GetByUniqueID("multi_test_2"):IsValid())["=="](true)
	T(clients.GetByUniqueID("multi_test_3"):IsValid())["=="](true)
	client1:Remove()
	client2:Remove()
	client3:Remove()
end)

T.Test("Clients registry non-existent client returns NULL", function()
	local client = clients.GetByUniqueID("nonexistent_client")
	T(client:IsValid())["=="](false)
end)

T.Test("Clients Create returns existing client if already exists", function()
	local client1 = clients.Create("duplicate_test", false)
	local client2 = clients.Create("duplicate_test", false)
	T(client1:GetUniqueID())["=="]("duplicate_test")
	T(client2:GetUniqueID())["=="]("duplicate_test")
	T(client1 == client2)["=="](true)
	client1:Remove()
end)

T.Test("Clients remove decreases count", function()
	local client1 = clients.Create("remove_test_1", false)
	local client2 = clients.Create("remove_test_2", false)
	T(#clients.GetAll())["=="](3)
	client1:Remove()
	T(#clients.GetAll())["=="](2)
	client2:Remove()
	T(#clients.GetAll())["=="](1)
end)

T.Test("Clients filter adds and removes clients", function()
	local client1 = clients.Create("filter_test_1", false)
	local client2 = clients.Create("filter_test_2", false)
	local client3 = clients.Create("filter_test_3", false)
	local filter = clients.CreateFilter()
	filter:Add(client1)
	filter:Add(client2)
	local all = filter:GetAll()
	T(#all)["=="](2)
	filter:Remove(client1)
	all = filter:GetAll()
	T(#all)["=="](1)
	T(all[1]:GetUniqueID())["=="]("filter_test_2")
	client1:Remove()
	client2:Remove()
	client3:Remove()
end)

T.Test("Clients filter GetAll returns empty for empty filter", function()
	local filter = clients.CreateFilter()
	local all = filter:GetAll()
	T(#all)["=="](0)
end)

T.Test("Clients bot creation", function()
	local bot = clients.CreateBot("TestBot", "bot_team")
	T(bot:IsValid())["=="](true)
	T(bot:IsBot())["=="](true)
	T(bot:GetNick())["~="](nil)
	T(bot:GetGroup())["~="](nil)
	bot:Remove()
end)

T.Test("Clients client properties get and set", function()
	local client = clients.Create("props_test", false)
	client:SetNick("NewNick")
	T(client:GetNick())["=="]("NewNick")
	client:SetGroup("new_group")
	T(client:GetGroup())["=="]("new_group")
	client:SetBot(true)
	T(client:IsBot())["=="](true)
	client:Remove()
end)

T.Test("Clients client unique color", function()
	local client = clients.Create("color_test", false)
	local color = client:GetUniqueColor()
	T(color)["~="](nil)
	T(color.r)["~="](nil)
	T(color.g)["~="](nil)
	T(color.b)["~="](nil)
	T(color.a)["~="](nil)
	client:Remove()
end)

T.Test("Clients client tostring includes unique ID", function()
	local client = clients.Create("tostring_test", false)
	local str = tostring(client)
	-- Verify the string contains the unique ID (using string.find with proper escaping)
	T(type(str))["=="]("string")
	T(#str)[">"](0)
	client:Remove()
end)

T.Test("Clients client valid check after remove", function()
	local client = clients.Create("valid_test", false)
	T(client:IsValid())["=="](true)
	client:Remove()
	T(client:IsValid())["=="](false)
end)
