local T = import("test/environment.lua")
local ffi = require("ffi")
local Buffer = import("goluwa/structs/buffer.lua")

T.Test("Buffer basic read operations", function()
	local buf = ffi.new("uint8_t[10]", {1, 2, 3, 4, 5, 6, 7, 8, 9, 10})
	local buffer = Buffer.New(buf, 10)
	T(buffer:ReadByte())["=="](1)
	T(buffer:ReadByte())["=="](2)
	T(buffer:ReadByte())["=="](3)
	buffer:Advance(2)
	T(buffer:ReadByte())["=="](6)
	buffer:Advance(-3)
	T(buffer:ReadByte())["=="](4)
end)

T.Test("Buffer write mode", function()
	local buf = ffi.new("uint8_t[5]")
	local buffer = Buffer.New(buf, 5):MakeWritable()
	buffer:WriteBytes("hello", 5)
	buffer:SetPosition(0)
	local str = buffer:ReadBytes(5)
	T(str)["=="]("hello")
end)

T.Test("Buffer grow", function()
	local buf = ffi.new("uint8_t[5]")
	local buffer = Buffer.New(buf, 5):MakeWritable()
	buffer:WriteBytes("hello world", 11)
	T(buffer:GetSize())[">="](11)
	buffer:SetPosition(0)
	local str = buffer:ReadBytes(11)
	T(str)["=="]("hello world")
end)
