local T = import("test/environment.lua")
local ffi = require("ffi")
local Buffer = import("goluwa/structs/buffer.lua")

T.Test("Buffer ReadBits basic", function()
	local buf = ffi.new("uint8_t[2]", {0b10101010, 0b11001100})
	local buffer = Buffer.New(buf, 2)
	buffer:RestartReadBits()
	T(buffer:ReadBits(4))["=="](0xA)
	T(buffer:ReadBits(4))["=="](0xA)
	T(buffer:ReadBits(8))["=="](0xCC)
end)

T.Test("Buffer ReadBits single bits", function()
	local buf = ffi.new("uint8_t[1]", {0b10110100})
	local buffer = Buffer.New(buf, 1)
	buffer:RestartReadBits()
	-- Read LSB to MSB
	T(buffer:ReadBits(1))["=="](0)
	T(buffer:ReadBits(1))["=="](0)
	T(buffer:ReadBits(1))["=="](1)
	T(buffer:ReadBits(1))["=="](0)
	T(buffer:ReadBits(1))["=="](1)
	T(buffer:ReadBits(1))["=="](1)
	T(buffer:ReadBits(1))["=="](0)
	T(buffer:ReadBits(1))["=="](1)
end)

T.Test("Buffer ReadBits various widths", function()
	local buf = ffi.new("uint8_t[4]", {0x12, 0x34, 0x56, 0x78})
	local buffer = Buffer.New(buf, 4)
	buffer:RestartReadBits()
	T(buffer:ReadBits(2))["=="](0x2)
	T(buffer:ReadBits(3))["=="](0x4)
	T(buffer:ReadBits(3))["=="](0x0)
	T(buffer:ReadBits(5))["=="](0x14)
	T(buffer:ReadBits(3))["=="](0x1)
end)

T.Test("Buffer ReadBits 16-bit values", function()
	local buf = ffi.new("uint8_t[2]", {0xFF, 0xFF})
	local buffer = Buffer.New(buf, 2)
	buffer:RestartReadBits()
	local val = buffer:ReadBits(16)
	T(val)["=="](0xFFFF)
end)

T.Test("Buffer ReadBits 24-bit values", function()
	local buf = ffi.new("uint8_t[3]", {0xFF, 0xFF, 0xFF})
	local buffer = Buffer.New(buf, 3)
	buffer:RestartReadBits()
	local val = buffer:ReadBits(24)
	T(val)["=="](0xFFFFFF)
end)

T.Test("Buffer ReadBits 32-bit values", function()
	local buf = ffi.new("uint8_t[4]", {0xFF, 0xFF, 0xFF, 0xFF})
	local buffer = Buffer.New(buf, 4)
	buffer:RestartReadBits()
	local val = buffer:ReadBits(32)
	T(val)["=="](0xFFFFFFFF)
end)

T.Test("Buffer ReadBits 48-bit values", function()
	local buf = ffi.new("uint8_t[6]", {0x76, 0x6F, 0x72, 0x62, 0x69, 0x73})
	local buffer = Buffer.New(buf, 6)
	buffer:RestartReadBits()
	local val = buffer:ReadBits(48)
	T(type(val))["=="]("number")
	T(val)["=="](0x736962726F76)
	T(buffer:RemainingBits())["=="](0)
end)

T.Test("Buffer ReadBits cross-byte boundary", function()
	local buf = ffi.new("uint8_t[2]", {0xAB, 0xCD})
	local buffer = Buffer.New(buf, 2)
	buffer:RestartReadBits()
	T(buffer:ReadBits(8))["=="](0xAB)
	T(buffer:ReadBits(8))["=="](0xCD)
end)

T.Test("Buffer ReadBits zero bits", function()
	local buf = ffi.new("uint8_t[1]", {0xFF})
	local buffer = Buffer.New(buf, 1)
	buffer:RestartReadBits()
	local val = buffer:ReadBits(0)
	T(val)["=="](0)
	T(buffer:ReadBits(8))["=="](0xFF)
end)

T.Test("Buffer ReadBits restart", function()
	local buf = ffi.new("uint8_t[2]", {0xAB, 0xCD})
	local buffer = Buffer.New(buf, 2)
	buffer:RestartReadBits()
	T(buffer:ReadBits(4))["=="](0xB)
	buffer:RestartReadBits()
	T(buffer:ReadBits(4))["=="](0xB)
end)

T.Test("Buffer BitsLeftInByte", function()
	local buf = ffi.new("uint8_t[2]", {0xFF, 0xFF})
	local buffer = Buffer.New(buf, 2)
	buffer:RestartReadBits()
	T(buffer:BitsLeftInByte())["=="](0)
	buffer:ReadBits(3)
	T(buffer:BitsLeftInByte())["=="](5)
	buffer:ReadBits(5)
	T(buffer:BitsLeftInByte())["=="](0)
	buffer:ReadBits(7)
	T(buffer:BitsLeftInByte())["=="](1)
end)

T.Test("Buffer BitPos and RemainingBits with peek", function()
	local buf = ffi.new("uint8_t[2]", {0xAB, 0xCD})
	local buffer = Buffer.New(buf, 2)
	buffer:RestartReadBits()
	T(buffer:BitPos())["=="](0)
	T(buffer:RemainingBits())["=="](16)
	T(buffer:PeekBits(5))["=="](0xB)
	T(buffer:BitPos())["=="](0)
	T(buffer:RemainingBits())["=="](16)
	T(buffer:ReadBits(3))["=="](0x3)
	T(buffer:BitPos())["=="](3)
	T(buffer:RemainingBits())["=="](13)
end)

T.Test("Buffer Read and Peek wrappers", function()
	local buffer = Buffer.New("vorbis\x01")
	buffer:RestartReadBits()
	T(buffer:Peek(48))["=="](0x736962726F76)
	T(buffer:BitPos())["=="](0)
	T(buffer:Read(48))["=="](0x736962726F76)
	T(buffer:Read(8))["=="](1)
	T(buffer:Read(8))["=="](0)
end)

T.Test("Buffer PeekBits basic", function()
	local buf = ffi.new("uint8_t[2]", {0xAB, 0xCD})
	local buffer = Buffer.New(buf, 2)
	buffer:RestartReadBits()
	-- Peek should not consume bits
	T(buffer:PeekBits(4))["=="](0xB)
	T(buffer:PeekBits(4))["=="](0xB)
	T(buffer:PeekBits(8))["=="](0xAB)
	-- Now consume and peek again
	buffer:SkipBits(4)
	T(buffer:PeekBits(4))["=="](0xA)
	T(buffer:PeekBits(8))["=="](0xDA)
end)

T.Test("Buffer PeekBits + SkipBits matches ReadBits", function()
	local buf1 = ffi.new("uint8_t[4]", {0x12, 0x34, 0x56, 0x78})
	local buf2 = ffi.new("uint8_t[4]", {0x12, 0x34, 0x56, 0x78})
	local b1 = Buffer.New(buf1, 4)
	local b2 = Buffer.New(buf2, 4)
	b1:RestartReadBits()
	b2:RestartReadBits()
	-- Read various widths with both methods and compare
	local widths = {3, 5, 7, 1, 8, 4, 4}

	for _, w in ipairs(widths) do
		local v1 = b1:ReadBits(w)
		local v2 = b2:PeekBits(w)
		b2:SkipBits(w)
		T(v1)["=="](v2)
	end
end)

T.Test("Buffer PeekBits 16-bit", function()
	local buf = ffi.new("uint8_t[3]", {0xFF, 0x00, 0xAA})
	local buffer = Buffer.New(buf, 3)
	buffer:RestartReadBits()
	T(buffer:PeekBits(16))["=="](0x00FF)
	buffer:SkipBits(8)
	T(buffer:PeekBits(16))["=="](0xAA00)
end)
