local T = import("test/environment.lua")
local ffi = require("ffi")
local Buffer = import("goluwa/structs/buffer.lua")

T.Test("Buffer WriteBoolean ReadBoolean true", function()
	local buf = ffi.new("uint8_t[4]")
	local buffer = Buffer.New(buf, 4)
	buffer:WriteBoolean(true)
	buffer:SetPosition(0)
	T(buffer:ReadBoolean())["=="](true)
end)

T.Test("Buffer WriteBoolean ReadBoolean false", function()
	local buf = ffi.new("uint8_t[4]")
	local buffer = Buffer.New(buf, 4)
	buffer:WriteBoolean(false)
	buffer:SetPosition(0)
	T(buffer:ReadBoolean())["=="](false)
end)

T.Test("Buffer WriteBoolean ReadBoolean boundary", function()
	local buf = ffi.new("uint8_t[4]")
	local buffer = Buffer.New(buf, 4)
	buffer:WriteByte(0)
	buffer:SetPosition(0)
	T(buffer:ReadBoolean())["=="](false)
	buffer:WriteByte(1)
	buffer:SetPosition(1)
	T(buffer:ReadBoolean())["=="](true)
	buffer:WriteByte(255)
	buffer:SetPosition(2)
	T(buffer:ReadBoolean())["=="](true)
end)

T.Test("Buffer WriteChar ReadChar", function()
	local buf = ffi.new("uint8_t[4]")
	local buffer = Buffer.New(buf, 4)
	buffer:WriteChar("A")
	buffer:SetPosition(0)
	T(buffer:ReadChar())["=="]("A")
end)

T.Test("Buffer WriteChar ReadChar all ascii", function()
	local buf = ffi.new("uint8_t[26]")
	local buffer = Buffer.New(buf, 26)
	for i = 0, 25 do
		buffer:WriteChar(string.char(65 + i))
	end
	buffer:SetPosition(0)
	for i = 0, 25 do
		T(buffer:ReadChar())["=="](string.char(65 + i))
	end
end)

T.Test("Buffer WriteChar ReadChar special chars", function()
	local buf = ffi.new("uint8_t[4]")
	local buffer = Buffer.New(buf, 4)
	buffer:WriteChar("\n")
	buffer:SetPosition(0)
	T(buffer:ReadChar())["=="]("\n")
	buffer:WriteChar("\0")
	buffer:SetPosition(1)
	T(buffer:ReadChar())["=="]("\0")
end)
