local T = import("test/environment.lua")
local ffi = require("ffi")
local Buffer = import("goluwa/structs/buffer.lua")

T.Test("Buffer U16 endianness", function()
	local buf = ffi.new("uint8_t[20]")
	local buffer = Buffer.New(buf, 20):MakeWritable()
	buffer:WriteU16LE(0x1234)
	buffer:WriteU16BE(0x1234)
	buffer:SetPosition(0)
	T(buffer:GetByte(0))["=="](0x34)
	T(buffer:GetByte(1))["=="](0x12)
	T(buffer:GetByte(2))["=="](0x12)
	T(buffer:GetByte(3))["=="](0x34)
	buffer:SetPosition(0)
	T(buffer:ReadU16LE())["=="](0x1234)
	T(buffer:ReadU16BE())["=="](0x1234)
end)

T.Test("Buffer U32 endianness", function()
	local buf = ffi.new("uint8_t[20]")
	local buffer = Buffer.New(buf, 20):MakeWritable()
	buffer:WriteU32LE(0x12345678)
	buffer:WriteU32BE(0x12345678)
	buffer:SetPosition(0)
	T(buffer:GetByte(0))["=="](0x78)
	T(buffer:GetByte(1))["=="](0x56)
	T(buffer:GetByte(2))["=="](0x34)
	T(buffer:GetByte(3))["=="](0x12)
	T(buffer:GetByte(4))["=="](0x12)
	T(buffer:GetByte(5))["=="](0x34)
	T(buffer:GetByte(6))["=="](0x56)
	T(buffer:GetByte(7))["=="](0x78)
	buffer:SetPosition(0)
	T(buffer:ReadU32LE())["=="](0x12345678)
	T(buffer:ReadU32BE())["=="](0x12345678)
end)

T.Test("Buffer I32 signed endianness", function()
	local buf = ffi.new("uint8_t[20]")
	local buffer = Buffer.New(buf, 20):MakeWritable()
	buffer:WriteI32LE(-1234567)
	buffer:WriteI32BE(-1234567)
	buffer:SetPosition(0)
	T(buffer:ReadI32LE())["=="](-1234567)
	T(buffer:ReadI32BE())["=="](-1234567)
end)

T.Test("Buffer U64 endianness", function()
	local buf = ffi.new("uint8_t[32]")
	local buffer = Buffer.New(buf, 32):MakeWritable()
	local value = 0x123456789ABCDEF0ULL
	buffer:WriteU64LE(value)
	buffer:WriteU64BE(value)
	buffer:SetPosition(0)
	T(buffer:GetByte(0))["=="](0xF0)
	T(buffer:GetByte(1))["=="](0xDE)
	T(buffer:GetByte(7))["=="](0x12)
	T(buffer:GetByte(8))["=="](0x12)
	T(buffer:GetByte(15))["=="](0xF0)
	buffer:SetPosition(0)
	T(buffer:ReadU64LE())["=="](value)
	T(buffer:ReadU64BE())["=="](value)
end)

T.Test("Buffer Float endianness", function()
	local buf = ffi.new("uint8_t[20]")
	local buffer = Buffer.New(buf, 20):MakeWritable()
	local test_value = 3.14159
	buffer:WriteFloatLE(test_value)
	buffer:WriteFloatBE(test_value)
	buffer:SetPosition(0)
	local le_byte0 = buffer:GetByte(0)
	local be_byte0 = buffer:GetByte(4)
	local le_byte3 = buffer:GetByte(3)
	local be_byte3 = buffer:GetByte(7)
	T(le_byte0)["=="](be_byte3)
	T(le_byte3)["=="](be_byte0)
	buffer:SetPosition(0)
	local read_le = buffer:ReadFloatLE()
	local read_be = buffer:ReadFloatBE()
	T(read_le)["~"](test_value)
	T(read_be)["~"](test_value)
end)

T.Test("Buffer Double endianness", function()
	local buf = ffi.new("uint8_t[32]")
	local buffer = Buffer.New(buf, 32):MakeWritable()
	local test_value = 3.141592653589793
	buffer:WriteDoubleLE(test_value)
	buffer:WriteDoubleBE(test_value)
	buffer:SetPosition(0)
	local le_byte0 = buffer:GetByte(0)
	local be_byte0 = buffer:GetByte(8)
	local le_byte7 = buffer:GetByte(7)
	local be_byte7 = buffer:GetByte(15)
	T(le_byte0)["=="](be_byte7)
	T(le_byte7)["=="](be_byte0)
	buffer:SetPosition(0)
	local read_le = buffer:ReadDoubleLE()
	local read_be = buffer:ReadDoubleBE()
	T(read_le)["~"](test_value)
	T(read_be)["~"](test_value)
end)

T.Test("Buffer I16 endianness", function()
	local buf = ffi.new("uint8_t[20]")
	local buffer = Buffer.New(buf, 20):MakeWritable()
	buffer:WriteI16LE(-12345)
	buffer:WriteI16BE(-12345)
	buffer:SetPosition(0)
	T(buffer:ReadI16LE())["=="](-12345)
	T(buffer:ReadI16BE())["=="](-12345)
end)

T.Test("Buffer I64 endianness", function()
	local buf = ffi.new("uint8_t[32]")
	local buffer = Buffer.New(buf, 32):MakeWritable()
	local value = -9223372036854775807LL
	buffer:WriteI64LE(value)
	buffer:WriteI64BE(value)
	buffer:SetPosition(0)
	T(buffer:ReadI64LE())["=="](value)
	T(buffer:ReadI64BE())["=="](value)
end)

T.Test("Buffer cross-endian compatibility", function()
	local buf = ffi.new("uint8_t[20]")
	local buffer = Buffer.New(buf, 20):MakeWritable()
	buffer:WriteU32LE(0x12345678)
	buffer:SetPosition(0)
	local swapped = buffer:ReadU32BE()
	T(swapped)["=="](0x78563412)
end)

T.Test("Buffer NaN handling with endianness", function()
	local buf = ffi.new("uint8_t[32]")
	local buffer = Buffer.New(buf, 32):MakeWritable()
	local nan = 0 / 0
	buffer:WriteFloatLE(nan)
	buffer:WriteFloatBE(nan)
	buffer:WriteDoubleLE(nan)
	buffer:WriteDoubleBE(nan)
	buffer:SetPosition(0)
	local f_le = buffer:ReadFloatLE()
	local f_be = buffer:ReadFloatBE()
	local d_le = buffer:ReadDoubleLE()
	local d_be = buffer:ReadDoubleBE()
	T(f_le ~= f_le)["=="](true)
	T(f_be ~= f_be)["=="](true)
	T(d_le ~= d_le)["=="](true)
	T(d_be ~= d_be)["=="](true)
end)
