local T = import("test/environment.lua")
local ffi = require("ffi")
local Buffer = import("goluwa/structs/buffer.lua")

T.Test("Buffer varint read/write", function()
	local buf = ffi.new("uint8_t[10]")
	local buffer = Buffer.New(buf, 10)
	buffer:WriteVariableSizedInteger(300)
	buffer:SetPosition(0)
	local val = buffer:ReadVarInt()
	T(val)["=="](300)
end)
