local T = import("test/environment.lua")
local ffi = require("ffi")
local Buffer = import("goluwa/structs/buffer.lua")

T.Test("Buffer WritePackedInteger ReadPackedInteger", function()
	local buf = ffi.new("uint8_t[10]")
	local buffer = Buffer.New(buf, 10)
	buffer:WritePackedInteger(0x12345678, 4, false)
	buffer:SetPosition(0)
	T(buffer:ReadPackedInteger(4, false))["=="](0x12345678)
end)

T.Test("Buffer WritePackedInteger ReadPackedInteger signed -1", function()
	local buf = ffi.new("uint8_t[10]")
	local buffer = Buffer.New(buf, 10)
	buffer:WritePackedInteger(-1, 4, true)
	buffer:SetPosition(0)
	T(buffer:ReadPackedInteger(4, true))["=="](-1)
end)

T.Test("Buffer WritePackedInteger ReadPackedInteger small value", function()
	local buf = ffi.new("uint8_t[10]")
	local buffer = Buffer.New(buf, 10)
	buffer:WritePackedInteger(42, 2, false)
	buffer:SetPosition(0)
	T(buffer:ReadPackedInteger(2, false))["=="](42)
end)

T.Test("Buffer WritePackedInteger ReadPackedInteger signed -128", function()
	local buf = ffi.new("uint8_t[10]")
	local buffer = Buffer.New(buf, 10)
	buffer:WritePackedInteger(-128, 1, true)
	buffer:SetPosition(0)
	T(buffer:ReadPackedInteger(1, true))["=="](-128)
end)

T.Test("Buffer WritePackedInteger ReadPackedInteger signed -32768", function()
	local buf = ffi.new("uint8_t[10]")
	local buffer = Buffer.New(buf, 10)
	buffer:WritePackedInteger(-32768, 2, true)
	buffer:SetPosition(0)
	T(buffer:ReadPackedInteger(2, true))["=="](-32768)
end)

T.Test("Buffer ReadVariableSizedInteger", function()
	local buf = ffi.new("uint8_t[10]")
	local buffer = Buffer.New(buf, 10):MakeWritable()
	buffer:WriteByte(0xAB)
	buffer:WriteByte(0x01)
	buffer:SetPosition(0)
	T(buffer:ReadVariableSizedInteger(2))["=="](171)
end)

T.Test("Buffer ReadVarInt basic", function()
	local buf = ffi.new("uint8_t[10]")
	local buffer = Buffer.New(buf, 10):MakeWritable()
	buffer:WriteByte(0xC3)
	buffer:WriteByte(0x01)
	buffer:SetPosition(0)
	T(buffer:ReadVarInt())["=="](195)
end)

T.Test("Buffer ReadVarInt signed", function()
	local buf = ffi.new("uint8_t[10]")
	local buffer = Buffer.New(buf, 10):MakeWritable()
	buffer:WriteByte(0xC3)
	buffer:WriteByte(0x01)
	buffer:SetPosition(0)
	T(buffer:ReadVarInt(true))["=="](195)
end)

T.Test("Buffer ReadULEB128 multi-byte", function()
	local buf = ffi.new("uint8_t[10]")
	local buffer = Buffer.New(buf, 10):MakeWritable()
	buffer:WriteByte(0xFF)
	buffer:WriteByte(0x7F)
	buffer:SetPosition(0)
	T(buffer:ReadULEB128())["=="](16383)
end)

T.Test("Buffer ReadULEB128 single byte", function()
	local buf = ffi.new("uint8_t[10]")
	local buffer = Buffer.New(buf, 10):MakeWritable()
	buffer:WriteByte(42)
	buffer:SetPosition(0)
	T(buffer:ReadULEB128())["=="](42)
end)

T.Test("Buffer WriteVariableSizedInteger ReadVarInt roundtrip", function()
	local buf = ffi.new("uint8_t[10]")
	local buffer = Buffer.New(buf, 10):MakeWritable()
	buffer:WriteVariableSizedInteger(300)
	buffer:SetPosition(0)
	T(buffer:ReadVarInt())["=="](300)
end)

T.Test("Buffer WriteVariableSizedInteger small value roundtrip", function()
	local buf = ffi.new("uint8_t[10]")
	local buffer = Buffer.New(buf, 10):MakeWritable()
	buffer:WriteVariableSizedInteger(42)
	buffer:SetPosition(0)
	T(buffer:ReadVarInt())["=="](42)
end)

T.Test("Buffer WriteVariableSizedInteger large value roundtrip", function()
	local buf = ffi.new("uint8_t[10]")
	local buffer = Buffer.New(buf, 10):MakeWritable()
	buffer:WriteVariableSizedInteger(0x7FFFFFFF)
	buffer:SetPosition(0)
	T(buffer:ReadVarInt())["=="](0x7FFFFFFF)
end)

T.Test("Buffer WriteSizedInteger ReadSizedInteger", function()
	local buf = ffi.new("uint8_t[10]")
	local buffer = Buffer.New(buf, 10)
	buffer:WriteSizedInteger(0x12345678, 4)
	buffer:SetPosition(0)
	T(buffer:ReadSizedInteger(4))["=="](0x12345678)
end)

T.Test("Buffer WriteSizedInteger ReadSizedInteger small", function()
	local buf = ffi.new("uint8_t[10]")
	local buffer = Buffer.New(buf, 10)
	buffer:WriteSizedInteger(100, 4)
	buffer:SetPosition(0)
	T(buffer:ReadSizedInteger(4))["=="](100)
end)
