local T = import("test/environment.lua")
local ffi = require("ffi")
local Buffer = import("goluwa/structs/buffer.lua")

T.Test("Buffer string read/write", function()
	local buf = ffi.new("uint8_t[20]")
	local buffer = Buffer.New(buf, 20)
	buffer:WriteStringNonNullterminated("hello world")
	buffer:SetPosition(0)
	local str = buffer:ReadStringNonNullterminated()
	T(str)["=="]("hello world")
end)

T.Test("Buffer find string", function()
	local buf = ffi.new("uint8_t[20]", "hello world, this is")
	local buffer = Buffer.New(buf, 20)
	local pos = buffer:FindNearest("this")
	T(buffer:GetStringSlice(pos - #"this", pos - 1))["=="]("this")
end)
