local T = import("test/environment.lua")
local ffi = require("ffi")
local Buffer = import("goluwa/structs/buffer.lua")

T.Test("Buffer ReadStringNonNullterminated", function()
	local buf = ffi.new("uint8_t[20]")
	local buffer = Buffer.New(buf, 20)
	buffer:WriteU32(5)
	buffer:WriteBytes("hello", 5)
	buffer:SetPosition(0)
	T(buffer:ReadStringNonNullterminated())["=="]("hello")
end)

T.Test("Buffer WriteStringNonNullterminated ReadStringNonNullterminated roundtrip", function()
	local buf = ffi.new("uint8_t[50]")
	local buffer = Buffer.New(buf, 50)
	buffer:WriteStringNonNullterminated("test string")
	buffer:SetPosition(0)
	T(buffer:ReadStringNonNullterminated())["=="]("test string")
end)

T.Test("Buffer IsStringSlice", function()
	local buf = ffi.new("uint8_t[10]")
	local buffer = Buffer.New(buf, 10):MakeWritable()
	buffer:WriteBytes("hello", 5)
	buffer:SetPosition(0)
	-- ffi strings are 0-indexed: Buffer[0]='h', Buffer[1]='e', etc.
	T(buffer:IsStringSlice(0, "hel"))["=="](true)
	T(buffer:IsStringSlice(0, "xyz"))["=="](false)
end)

T.Test("Buffer IsStringSlice2", function()
	local buf = ffi.new("uint8_t[10]")
	local buffer = Buffer.New(buf, 10):MakeWritable()
	buffer:WriteBytes("hello", 5)
	buffer:SetPosition(0)
	T(buffer:IsStringSlice2(0, 2, "hel"))["=="](true)
	T(buffer:IsStringSlice2(0, 3, "hell"))["=="](true) -- 0..3 is 4 chars, matches "hell"
	T(buffer:IsStringSlice2(0, 2, "xyz"))["=="](false)
end)

T.Test("Buffer FindNearest", function()
	local buf = ffi.new("uint8_t[20]")
	local buffer = Buffer.New(buf, 20):MakeWritable()
	buffer:WriteBytes("hello world", 11)
	buffer:SetPosition(1)
	local pos = buffer:FindNearest("world")
	-- FindNearest returns i + #str where i is the match start position
	T(pos)["=="](11)
end)

T.Test("Buffer ReadAll", function()
	local buf = ffi.new("uint8_t[10]")
	local buffer = Buffer.New(buf, 10):MakeWritable()
	buffer:WriteBytes("abcde", 5)
	buffer:SetPosition(1)
	-- ReadAll reads from current position to end of buffer
	local result = buffer:ReadAll()
	T(#result)["=="](10) -- reads entire buffer from position 1
end)

T.Test("Buffer ReadVariableSizedInteger single byte", function()
	local buf = ffi.new("uint8_t[10]")
	local buffer = Buffer.New(buf, 10):MakeWritable()
	buffer:WriteByte(42) -- no continuation bit
	buffer:SetPosition(0)
	T(buffer:ReadVariableSizedInteger(1))["=="](42)
end)

T.Test("Buffer ReadVariableSizedInteger two bytes", function()
	local buf = ffi.new("uint8_t[10]")
	local buffer = Buffer.New(buf, 10):MakeWritable()
	-- 300 = 0x12C = bytes: 0xAC (continuation), 0x02 (no continuation)
	buffer:WriteByte(0xAC)
	buffer:WriteByte(0x02)
	buffer:SetPosition(0)
	T(buffer:ReadVariableSizedInteger(2))["=="](300)
end)

T.Test("Buffer ReadSizedInteger single byte", function()
	local buf = ffi.new("uint8_t[10]")
	local buffer = Buffer.New(buf, 10)
	buffer:WriteSizedInteger(42, 1)
	buffer:SetPosition(0)
	T(buffer:ReadSizedInteger(1))["=="](42)
end)

T.Test("Buffer ReadSizedInteger two bytes", function()
	local buf = ffi.new("uint8_t[10]")
	local buffer = Buffer.New(buf, 10)
	buffer:WriteSizedInteger(300, 2)
	buffer:SetPosition(0)
	T(buffer:ReadSizedInteger(2))["=="](300)
end)

T.Test("Buffer WriteStringNonNullterminated empty string", function()
	local buf = ffi.new("uint8_t[10]")
	local buffer = Buffer.New(buf, 10)
	buffer:WriteStringNonNullterminated("")
	buffer:SetPosition(0)
	T(buffer:ReadStringNonNullterminated())["=="]("")
end)

T.Test("Buffer IsStringSlice empty string", function()
	local buf = ffi.new("uint8_t[10]")
	local buffer = Buffer.New(buf, 10):MakeWritable()
	buffer:WriteBytes("hello", 5)
	buffer:SetPosition(0)
	T(buffer:IsStringSlice(0, ""))["=="](true)
end)
