local T = import("test/environment.lua")
local ffi = require("ffi")
local Buffer = import("goluwa/structs/buffer.lua")

T.Test("Buffer ReadStringNonNullterminated", function()
	local buf = ffi.new("uint8_t[20]")
	local buffer = Buffer.New(buf, 20)
	buffer:WriteU32(5)
	buffer:WriteBytes("hello", 5)
	buffer:SetPosition(0)
	T(buffer:ReadStringNonNullterminated())["=="]("hello")
end)

T.Test("Buffer WriteStringNonNullterminated ReadStringNonNullterminated roundtrip", function()
	local buf = ffi.new("uint8_t[50]")
	local buffer = Buffer.New(buf, 50)
	buffer:WriteStringNonNullterminated("test string")
	buffer:SetPosition(0)
	T(buffer:ReadStringNonNullterminated())["=="]("test string")
end)

T.Test("Buffer IsStringSlice", function()
	local buf = ffi.new("uint8_t[10]")
	local buffer = Buffer.New(buf, 10):MakeWritable()
	buffer:WriteBytes("hello", 5)
	buffer:SetPosition(0)
	T(buffer:IsStringSlice(0, "hel"))["=="](true)
	T(buffer:IsStringSlice(0, "xyz"))["=="](false)
end)

T.Test("Buffer IsStringSlice2", function()
	local buf = ffi.new("uint8_t[10]")
	local buffer = Buffer.New(buf, 10):MakeWritable()
	buffer:WriteBytes("hello", 5)
	buffer:SetPosition(0)
	T(buffer:IsStringSlice2(0, 2, "hel"))["=="](true)
	T(buffer:IsStringSlice2(0, 3, "hell"))["=="](true)
	T(buffer:IsStringSlice2(0, 2, "xyz"))["=="](false)
end)

T.Test("Buffer FindNearest", function()
	local buf = ffi.new("uint8_t[20]")
	local buffer = Buffer.New(buf, 20):MakeWritable()
	buffer:WriteBytes("hello world", 11)
	buffer:SetPosition(1)
	local pos = buffer:FindNearest("world")
	T(pos)["=="](11)
end)

T.Test("Buffer ReadAll", function()
	local buf = ffi.new("uint8_t[10]")
	local buffer = Buffer.New(buf, 10):MakeWritable()
	buffer:WriteBytes("abcde", 5)
	buffer:SetPosition(1)
	local result = buffer:ReadAll()
	T(#result)["=="](10)
end)

T.Test("Buffer ReadVariableSizedInteger single byte", function()
	local buf = ffi.new("uint8_t[10]")
	local buffer = Buffer.New(buf, 10):MakeWritable()
	buffer:WriteByte(42)
	buffer:SetPosition(0)
	T(buffer:ReadVariableSizedInteger(1))["=="](42)
end)

T.Test("Buffer ReadVariableSizedInteger two bytes", function()
	local buf = ffi.new("uint8_t[10]")
	local buffer = Buffer.New(buf, 10):MakeWritable()
	buffer:WriteByte(0xAC)
	buffer:WriteByte(0x02)
	buffer:SetPosition(0)
	T(buffer:ReadVariableSizedInteger(2))["=="](300)
end)

T.Test("Buffer ReadSizedInteger single byte", function()
	local buf = ffi.new("uint8_t[10]")
	local buffer = Buffer.New(buf, 10)
	buffer:WriteSizedInteger(42, 1)
	buffer:SetPosition(0)
	T(buffer:ReadSizedInteger(1))["=="](42)
end)

T.Test("Buffer ReadSizedInteger two bytes", function()
	local buf = ffi.new("uint8_t[10]")
	local buffer = Buffer.New(buf, 10)
	buffer:WriteSizedInteger(300, 2)
	buffer:SetPosition(0)
	T(buffer:ReadSizedInteger(2))["=="](300)
end)

T.Test("Buffer WriteStringNonNullterminated empty string", function()
	local buf = ffi.new("uint8_t[10]")
	local buffer = Buffer.New(buf, 10)
	buffer:WriteStringNonNullterminated("")
	buffer:SetPosition(0)
	T(buffer:ReadStringNonNullterminated())["=="]("")
end)

T.Test("Buffer IsStringSlice empty string", function()
	local buf = ffi.new("uint8_t[10]")
	local buffer = Buffer.New(buf, 10):MakeWritable()
	buffer:WriteBytes("hello", 5)
	buffer:SetPosition(0)
	T(buffer:IsStringSlice(0, ""))["=="](true)
end)
