local T = import("test/environment.lua")
local ffi = require("ffi")
local Buffer = import("goluwa/structs/buffer.lua")

T.Test("Buffer ReadBytesUntil finds delimiter", function()
	local buf = ffi.new("uint8_t[20]", "hello, world, test")
	local buffer = Buffer.New(buf, 20)
	local str = buffer:ReadBytesUntil(", ")
	T(str)["=="]("hello")
	-- Should have consumed the delimiter too
	T(buffer:GetPosition())["=="](7)
end)

T.Test("Buffer ReadBytesUntil returns false on missing delimiter", function()
	local buf = ffi.new("uint8_t[10]", "hello world")
	local buffer = Buffer.New(buf, 10)
	local result = buffer:ReadBytesUntil(", ")
	T(result)["=="](false)
end)

T.Test("Buffer FindString finds substring", function()
	local buf = ffi.new("uint8_t[20]", "hello world, this is")
	local buffer = Buffer.New(buf, 20)
	local pos = buffer:FindString("this")
	T(pos)["=="](11)
end)

T.Test("Buffer FindString returns false when not found", function()
	local buf = ffi.new("uint8_t[10]", "hello world")
	local buffer = Buffer.New(buf, 10)
	local pos = buffer:FindString("xyz")
	T(pos)["=="](false)
end)

T.Test("Buffer FindString preserves position", function()
	local buf = ffi.new("uint8_t[20]", "hello world, this is")
	local buffer = Buffer.New(buf, 20)
	buffer:Advance(5)
	T(buffer:GetPosition())["=="](5)
	buffer:FindString("this")
	T(buffer:GetPosition())["=="](5)
end)

T.Test("Buffer IterateStrings iterates null-terminated strings", function()
	local buf = ffi.new("uint8_t[20]", "hello\0world\0test\0")
	local buffer = Buffer.New(buf, 20)
	local results = {}
	for str in buffer:IterateStrings() do
		table.insert(results, str)
	end
	T(#results)["=="](3)
	T(results[1])["=="]("hello")
	T(results[2])["=="]("world")
	T(results[3])["=="]("test")
end)

T.Test("Buffer ReadString null-terminated", function()
	local buf = ffi.new("uint8_t[20]", "hello\0world\0")
	local buffer = Buffer.New(buf, 20)
	local str = buffer:ReadString()
	T(str)["=="]("hello")
end)

T.Test("Buffer ReadString with length", function()
	local buf = ffi.new("uint8_t[20]", "hello world")
	local buffer = Buffer.New(buf, 20)
	local str = buffer:ReadString(5)
	T(str)["=="]("hello")
	T(buffer:GetPosition())["=="](5)
end)

T.Test("Buffer ReadFixedLengthString reads exact length", function()
	local buf = ffi.new("uint8_t[20]", "hello world")
	local buffer = Buffer.New(buf, 20)
	local str = buffer:ReadFixedLengthString(5)
	T(str)["=="]("hello")
end)

T.Test("Buffer WriteString writes null-terminated", function()
	local buf = ffi.new("uint8_t[20]")
	local buffer = Buffer.New(buf, 20):MakeWritable()
	buffer:WriteString("hi")
	buffer:SetPosition(0)
	local str = buffer:ReadString()
	T(str)["=="]("hi")
end)
